// apps/web/src/components/landing/AboutSection.tsx
import {
    Target,
    Eye,
    Shield,
    TrendingUp,
    Heart,
    Users,
    Award,
    Leaf
} from 'lucide-react';

const values = [
    { icon: Award, label: 'Calidad' },
    { icon: TrendingUp, label: 'Eficiencia' },
    { icon: Target, label: 'Efectividad' },
    { icon: Shield, label: 'Seguridad' },
    { icon: Heart, label: 'Responsabilidad' },
    { icon: Users, label: 'Trabajo en Equipo' },
    { icon: Leaf, label: 'Desarrollo Sostenible' },
];

export default function AboutSection() {
    return (
        <section id="nosotros" className="py-24 bg-white dark:bg-gray-900">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="grid lg:grid-cols-2 gap-16 items-center">
                    {/* Content */}
                    <div>
                        {/* Badge */}
                        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-50 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/20 mb-6">
                            <span className="text-sm font-medium text-blue-700 dark:text-blue-400">
                                Sobre Nosotros
                            </span>
                        </div>

                        <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-6">
                            Más de <span className="gradient-text">15 años</span> construyendo confianza
                        </h2>

                        {/* Mission */}
                        <div className="mb-8">
                            <div className="flex items-center gap-3 mb-3">
                                <div className="w-10 h-10 rounded-lg gradient-bg flex items-center justify-center">
                                    <Target className="w-5 h-5 text-white" />
                                </div>
                                <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                                    Misión
                                </h3>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400 leading-relaxed pl-13">
                                Prestar en todo el territorio nacional un servicio eficiente en construcción,
                                mantenimiento, montajes de obras civiles, eléctricas, refrigeración,
                                telecomunicaciones, suministros de materiales, equipos y personal técnico,
                                contando con un recurso humano altamente calificado y tecnología de última generación.
                            </p>
                        </div>

                        {/* Vision */}
                        <div className="mb-8">
                            <div className="flex items-center gap-3 mb-3">
                                <div className="w-10 h-10 rounded-lg bg-green-600 flex items-center justify-center">
                                    <Eye className="w-5 h-5 text-white" />
                                </div>
                                <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                                    Visión 2026
                                </h3>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400 leading-relaxed pl-13">
                                Ser una empresa rentable, sólida y en continuo crecimiento, con la mayor
                                participación en el mercado nacional, por la idoneidad de su personal competente,
                                tecnología de última generación, responsabilidad social, alto desempeño y
                                compromiso con el desarrollo sostenible.
                            </p>
                        </div>

                        {/* Stats */}
                        <div className="grid grid-cols-3 gap-6 pt-6 border-t border-gray-200 dark:border-gray-700">
                            <div className="text-center">
                                <div className="text-3xl font-bold gradient-text">12</div>
                                <div className="text-sm text-gray-500 dark:text-gray-400">Junio 2008</div>
                            </div>
                            <div className="text-center">
                                <div className="text-3xl font-bold gradient-text">5</div>
                                <div className="text-sm text-gray-500 dark:text-gray-400">Áreas de Servicio</div>
                            </div>
                            <div className="text-center">
                                <div className="text-3xl font-bold gradient-text">100%</div>
                                <div className="text-sm text-gray-500 dark:text-gray-400">Compromiso</div>
                            </div>
                        </div>
                    </div>

                    {/* Values Card */}
                    <div className="relative">
                        {/* Background Decoration */}
                        <div className="absolute inset-0 gradient-bg rounded-3xl blur-3xl opacity-10" />

                        <div className="relative glass rounded-3xl p-8 border border-gray-200/50 dark:border-gray-700/50">
                            <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-6 text-center">
                                Nuestros Valores
                            </h3>

                            <div className="grid grid-cols-2 gap-4">
                                {values.map((value, index) => {
                                    const Icon = value.icon;
                                    return (
                                        <div
                                            key={index}
                                            className="flex items-center gap-3 p-4 rounded-xl bg-gray-50 dark:bg-gray-800/50 transition-all duration-300 hover:bg-gray-100 dark:hover:bg-gray-800"
                                        >
                                            <div className="w-10 h-10 rounded-lg bg-blue-100 dark:bg-blue-500/20 flex items-center justify-center flex-shrink-0">
                                                <Icon className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                                            </div>
                                            <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
                                                {value.label}
                                            </span>
                                        </div>
                                    );
                                })}
                            </div>

                            {/* Certifications */}
                            <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
                                <p className="text-center text-sm text-gray-500 dark:text-gray-400 mb-4">
                                    Certificaciones y Políticas
                                </p>
                                <div className="flex flex-wrap justify-center gap-2">
                                    {['SG-SST', 'PESV', 'Calidad', 'Ambiental'].map((cert, index) => (
                                        <span
                                            key={index}
                                            className="px-3 py-1 text-xs font-medium rounded-full bg-green-50 dark:bg-green-500/10 text-green-700 dark:text-green-400 border border-green-200 dark:border-green-500/20"
                                        >
                                            {cert}
                                        </span>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
}

// frontend/src/app/shared/components/landing/about-section/about-section.component.ts
/**
 * About Section Component - Migrado de Next.js
 * @see apps/web-old/src/components/landing/AboutSection.tsx
 */

import { Component } from '@angular/core';


interface Value {
  icon: string;
  label: string;
}

@Component({
  selector: 'app-about-section',
  standalone: true,
  imports: [],
  templateUrl: './about-section.component.html',
  styleUrl: './about-section.component.css'
})
export class AboutSectionComponent {
  values: Value[] = [
    { icon: 'award', label: 'Calidad' },
    { icon: 'trending-up', label: 'Eficiencia' },
    { icon: 'target', label: 'Efectividad' },
    { icon: 'shield', label: 'Seguridad' },
    { icon: 'heart', label: 'Responsabilidad' },
    { icon: 'users', label: 'Trabajo en Equipo' },
    { icon: 'leaf', label: 'Desarrollo Sostenible' },
  ];

  certifications = ['SG-SST', 'PESV', 'Calidad', 'Ambiental'];

  getIconSvg(icon: string): string {
    const icons: Record<string, string> = {
      award: 'M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z',
      'trending-up': 'M13 7h8m0 0v8m0-8l-8 8-4-4-6 6',
      target: 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z',
      shield: 'M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z',
      heart: 'M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z',
      users: 'M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z',
      leaf: 'M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253',
    };
    return icons[icon] || icons['award'];
  }
}


<section id="nosotros" class="py-24 bg-white dark:bg-gray-900">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="grid lg:grid-cols-2 gap-16 items-center">
      <!-- Content -->
      <div>
        <!-- Badge -->
        <div
          class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-50 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/20 mb-6"
        >
          <span class="text-sm font-medium text-blue-700 dark:text-blue-400"> Sobre Nosotros </span>
        </div>

        <h2 class="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-6">
          Más de <span class="gradient-text">15 años</span> construyendo confianza
        </h2>

        <!-- Mission -->
        <div class="mb-8">
          <div class="flex items-center gap-3 mb-3">
            <div class="w-10 h-10 rounded-lg gradient-bg flex items-center justify-center">
              <svg class="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
                />
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 dark:text-white">Misión</h3>
          </div>
          <p class="text-gray-600 dark:text-gray-400 leading-relaxed pl-[3.25rem]">
            Prestar en todo el territorio nacional un servicio eficiente en construcción,
            mantenimiento, montajes de obras civiles, eléctricas, refrigeración, telecomunicaciones,
            suministros de materiales, equipos y personal técnico, contando con un recurso humano
            altamente calificado y tecnología de última generación.
          </p>
        </div>

        <!-- Vision -->
        <div class="mb-8">
          <div class="flex items-center gap-3 mb-3">
            <div class="w-10 h-10 rounded-lg bg-green-600 flex items-center justify-center">
              <svg class="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                />
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
                />
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 dark:text-white">Visión 2026</h3>
          </div>
          <p class="text-gray-600 dark:text-gray-400 leading-relaxed pl-[3.25rem]">
            Ser una empresa rentable, sólida y en continuo crecimiento, con la mayor participación
            en el mercado nacional, por la idoneidad de su personal competente, tecnología de última
            generación, responsabilidad social, alto desempeño y compromiso con el desarrollo
            sostenible.
          </p>
        </div>

        <!-- Stats -->
        <div class="grid grid-cols-3 gap-6 pt-6 border-t border-gray-200 dark:border-gray-700">
          <div class="text-center">
            <div class="text-3xl font-bold gradient-text">12</div>
            <div class="text-sm text-gray-500 dark:text-gray-400">Junio 2008</div>
          </div>
          <div class="text-center">
            <div class="text-3xl font-bold gradient-text">5</div>
            <div class="text-sm text-gray-500 dark:text-gray-400">Áreas de Servicio</div>
          </div>
          <div class="text-center">
            <div class="text-3xl font-bold gradient-text">100%</div>
            <div class="text-sm text-gray-500 dark:text-gray-400">Compromiso</div>
          </div>
        </div>
      </div>

      <!-- Values Card -->
      <div class="relative">
        <!-- Background Decoration -->
        <div class="absolute inset-0 gradient-bg rounded-3xl blur-3xl opacity-10"></div>

        <div
          class="relative glass rounded-3xl p-8 border border-gray-200/50 dark:border-gray-700/50"
        >
          <h3 class="text-2xl font-bold text-gray-900 dark:text-white mb-6 text-center">
            Nuestros Valores
          </h3>

          <div class="grid grid-cols-2 gap-4">
            @for (value of values; track value.label) {
              <div
                class="flex items-center gap-3 p-4 rounded-xl bg-gray-50 dark:bg-gray-800/50 transition-all duration-300 hover:bg-gray-100 dark:hover:bg-gray-800"
              >
                <div
                  class="w-10 h-10 rounded-lg bg-blue-100 dark:bg-blue-500/20 flex items-center justify-center flex-shrink-0"
                >
                  <svg
                    class="w-5 h-5 text-blue-600 dark:text-blue-400"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      [attr.d]="getIconSvg(value.icon)"
                    />
                  </svg>
                </div>
                <span class="text-sm font-medium text-gray-700 dark:text-gray-300">
                  {{ value.label }}
                </span>
              </div>
            }
          </div>

          <!-- Certifications -->
          <div class="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
            <p class="text-center text-sm text-gray-500 dark:text-gray-400 mb-4">
              Certificaciones y Políticas
            </p>
            <div class="flex flex-wrap justify-center gap-2">
              @for (cert of certifications; track cert) {
                <span
                  class="px-3 py-1 text-xs font-medium rounded-full bg-green-50 dark:bg-green-500/10 text-green-700 dark:text-green-400 border border-green-200 dark:border-green-500/20"
                >
                  {{ cert }}
                </span>
              }
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
