// frontend/src/app/shared/components/landing/landing-footer/landing-footer.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { CompanyDataService } from '../../../../core/services/company-data.service';

@Component({
  selector: 'app-landing-footer',
  imports: [CommonModule],
  template: `
    <footer
      class="bg-slate-100 py-16 text-slate-900 dark:bg-slate-950 dark:text-white"
      role="contentinfo"
    >
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="grid gap-10 md:grid-cols-4">
          <section aria-labelledby="footer-company">
            <h2 id="footer-company" class="text-lg font-semibold">CERMONT S.A.S.</h2>
            <p class="mt-4 text-sm/7 text-slate-600 dark:text-white/70">
              Mas de {{ companyData.experience() }} anos aportando soluciones en construccion,
              energia, refrigeracion y telecomunicaciones.
            </p>
            <div class="mt-4 flex gap-2">
              @for (cert of companyData.getCertifications(); track cert.acronym) {
                <span
                  class="rounded-full bg-slate-200 px-3 py-1 text-xs font-semibold text-slate-600 dark:bg-white/10 dark:text-white/70"
                >
                  {{ cert.acronym }}
                </span>
              }
            </div>
          </section>

          <nav aria-labelledby="footer-services">
            <h2
              id="footer-services"
              class="text-sm font-semibold uppercase tracking-[0.3em] text-slate-500 dark:text-white/60"
            >
              Servicios
            </h2>
            <ul class="mt-4 space-y-2 text-sm text-slate-600 dark:text-white/70">
              <li>
                <a href="#servicios" class="transition hover:text-slate-900 dark:hover:text-white"
                  >Construccion</a
                >
              </li>
              <li>
                <a href="#servicios" class="transition hover:text-slate-900 dark:hover:text-white"
                  >Electricidad</a
                >
              </li>
              <li>
                <a href="#servicios" class="transition hover:text-slate-900 dark:hover:text-white"
                  >Refrigeracion</a
                >
              </li>
              <li>
                <a href="#servicios" class="transition hover:text-slate-900 dark:hover:text-white"
                  >Montajes</a
                >
              </li>
              <li>
                <a href="#servicios" class="transition hover:text-slate-900 dark:hover:text-white">
                  Telecomunicaciones
                </a>
              </li>
            </ul>
          </nav>

          <nav aria-labelledby="footer-company-links">
            <h2
              id="footer-company-links"
              class="text-sm font-semibold uppercase tracking-[0.3em] text-slate-500 dark:text-white/60"
            >
              Empresa
            </h2>
            <ul class="mt-4 space-y-2 text-sm text-slate-600 dark:text-white/70">
              <li>
                <a href="#about" class="transition hover:text-slate-900 dark:hover:text-white"
                  >Nosotros</a
                >
              </li>
              <li>
                <a href="#about" class="transition hover:text-slate-900 dark:hover:text-white"
                  >Mision y vision</a
                >
              </li>
              <li>
                <a href="#about" class="transition hover:text-slate-900 dark:hover:text-white"
                  >Certificaciones</a
                >
              </li>
              <li>
                <a href="#contacto" class="transition hover:text-slate-900 dark:hover:text-white"
                  >Contacto</a
                >
              </li>
            </ul>
          </nav>

          <address class="not-italic" aria-labelledby="footer-contact">
            <h2
              id="footer-contact"
              class="text-sm font-semibold uppercase tracking-[0.3em] text-slate-500 dark:text-white/60"
            >
              Contacto
            </h2>
            <dl class="mt-4 space-y-4 text-sm text-slate-600 dark:text-white/70">
              <div>
                <dt class="text-xs uppercase tracking-[0.3em] text-slate-400 dark:text-white/50">
                  Telefonos
                </dt>
                <dd class="mt-2">
                  <a
                    [href]="phoneLink()"
                    class="transition hover:text-slate-900 dark:hover:text-white"
                    >{{ contact.phone }}</a
                  ><br />
                  <a
                    [href]="mobileLink()"
                    class="transition hover:text-slate-900 dark:hover:text-white"
                    >{{ contact.mobile }}</a
                  >
                </dd>
              </div>
              <div>
                <dt class="text-xs uppercase tracking-[0.3em] text-slate-400 dark:text-white/50">
                  Email
                </dt>
                <dd class="mt-2">
                  <a
                    [href]="emailLink()"
                    class="transition hover:text-slate-900 dark:hover:text-white"
                    >{{ contact.email }}</a
                  >
                </dd>
              </div>
              <div>
                <dt class="text-xs uppercase tracking-[0.3em] text-slate-400 dark:text-white/50">
                  Ubicacion
                </dt>
                <dd class="mt-2">{{ contact.address }}</dd>
              </div>
            </dl>
          </address>
        </div>

        <div
          class="mt-12 border-t border-slate-200 pt-8 text-center text-xs text-slate-500 dark:border-white/10 dark:text-white/50"
        >
          © <time [attr.datetime]="currentYear">{{ currentYear }}</time> CERMONT S.A.S. Todos los
          derechos reservados.
        </div>
      </div>
    </footer>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LandingFooterComponent {
  readonly companyData = inject(CompanyDataService);
  readonly contact = this.companyData.getContact();
  readonly currentYear = new Date().getFullYear();

  phoneLink = computed(() => `tel:${this.contact.phone.replace(/\s/g, '')}`);
  mobileLink = computed(() => `tel:${this.contact.mobile.replace(/\s/g, '')}`);
  emailLink = computed(() => `mailto:${this.contact.email}`);
}

// frontend/src/landing/components/LandingFooter.tsx
import { Mail, MapPin, PhoneCall } from "lucide-react";
import Link from "next/link";
import { BadgePill } from "@/core/ui/BadgePill";
import { Button } from "@/core/ui/Button";
import { Logo } from "@/core/ui/Logo";
import {
	CORPORATE_ADDRESS_ARAUCA,
	CORPORATE_ADDRESS_BOGOTA,
	CORPORATE_CELULAR,
	CORPORATE_EMAIL,
	CORPORATE_MAILTO,
	CORPORATE_NAME,
	CORPORATE_NIT,
	CORPORATE_PHONE_ARAUCA,
	CORPORATE_PHONE_BOGOTA,
	NAV_ITEMS,
} from "../landing-constants";
import { LANDING_RESOURCES } from "../landing-data";

export function LandingFooter() {
	return (
		<footer className="border-t border-white/10 bg-cermont-bg-deep">
			<div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
				<div className="grid gap-10 lg:grid-cols-[1.2fr_0.9fr_0.95fr_0.95fr]">
					<div>
						<Logo href="/" className="gap-3" size="md" wordmarkClassName="text-white" />
						<p className="mt-4 max-w-md text-sm leading-6 text-slate-400">
							{CORPORATE_NAME}. presta servicios de construccion, electricidad, refrigeracion,
							telecomunicaciones y montajes con disciplina, seguridad y trazabilidad. NIT{" "}
							{CORPORATE_NIT}.
						</p>

						<div className="mt-5 flex flex-wrap gap-2">
							{["Calidad", "Seguridad", "Trazabilidad"].map((item) => (
								<BadgePill
									key={item}
									className="border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-slate-200"
									dotClassName="bg-cermont-blue-light"
									ariaLabel={item}
								>
									{item}
								</BadgePill>
							))}
						</div>
					</div>

					<nav aria-label="Navegacion de empresa">
						<h3 className="mb-4 text-xs font-bold uppercase tracking-widest text-slate-300">
							Empresa
						</h3>
						<ul className="space-y-2.5">
							{NAV_ITEMS.map(({ label, href }) => (
								<li key={label}>
									<a
										href={href}
										className="text-sm text-slate-500 transition-colors hover:text-white"
									>
										{label}
									</a>
								</li>
							))}
							<li>
								<Link
									href="/login"
									className="text-sm text-slate-500 transition-colors hover:text-white"
								>
									Acceso privado
								</Link>
							</li>
						</ul>
					</nav>

					<nav aria-label="Documentos y descargas">
						<h3 className="mb-4 text-xs font-bold uppercase tracking-widest text-slate-300">
							Documentos
						</h3>
						<ul className="space-y-2.5">
							{LANDING_RESOURCES.map(({ title, href }) => (
								<li key={title}>
									<a
										href={href}
										download
										className="text-sm text-slate-500 transition-colors hover:text-white"
									>
										{title}
									</a>
								</li>
							))}
						</ul>
					</nav>

					<div>
						<h3 className="mb-4 text-xs font-bold uppercase tracking-widest text-slate-300">
							Contacto
						</h3>
						<div className="space-y-2.5 text-sm text-slate-500">
							<a
								href={CORPORATE_MAILTO}
								className="flex items-center gap-2 transition-colors hover:text-white"
							>
								<Mail className="h-3.5 w-3.5" aria-hidden="true" />
								{CORPORATE_EMAIL}
							</a>
							<div className="flex items-start gap-2">
								<MapPin className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden="true" />
								<div>
									<p>{CORPORATE_ADDRESS_ARAUCA}</p>
									<p className="mt-1">{CORPORATE_ADDRESS_BOGOTA}</p>
								</div>
							</div>
							<div className="flex items-center gap-2">
								<PhoneCall className="h-3.5 w-3.5" aria-hidden="true" />
								<span>
									{CORPORATE_PHONE_ARAUCA} / {CORPORATE_PHONE_BOGOTA}
								</span>
							</div>
							<div className="flex items-center gap-2">
								<PhoneCall className="h-3.5 w-3.5" aria-hidden="true" />
								<span>{CORPORATE_CELULAR}</span>
							</div>
						</div>

						<div className="mt-6">
							<Button asChild className="rounded-full px-5">
								<Link href="/login">Ingresar al sistema</Link>
							</Button>
						</div>
					</div>
				</div>

				<div className="mt-10 flex flex-col gap-4 border-t border-white/10 pt-8 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between">
					<p>
						&copy; {new Date().getFullYear()} {CORPORATE_NAME}. Todos los derechos reservados.
					</p>
					<p>NIT {CORPORATE_NIT}</p>
				</div>
			</div>
		</footer>
	);
}
