// apps/web/src/components/ui/SpotlightCard.tsx
'use client';

import { useRef, useState, useEffect } from 'react';
import { cn } from '@/lib/utils';

interface SpotlightCardProps extends React.HTMLAttributes<HTMLDivElement> {
    children: ReactNode;
    spotlightColor?: string;
    className?: string;
}

import { type ReactNode } from 'react';

export function SpotlightCard({
    children,
    className = '',
    spotlightColor = 'rgba(255, 255, 255, 0.1)',
    ...props
}: SpotlightCardProps) {
    const divRef = useRef<HTMLDivElement>(null);
    const [position, setPosition] = useState({ x: 0, y: 0 });
    const [opacity, setOpacity] = useState(0);

    const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
        if (!divRef.current) return;

        const div = divRef.current;
        const rect = div.getBoundingClientRect();

        setPosition({ x: e.clientX - rect.left, y: e.clientY - rect.top });
    };

    const handleMouseEnter = () => {
        setOpacity(1);
    };

    const handleMouseLeave = () => {
        setOpacity(0);
    };

    return (
        <div
            ref={divRef}
            onMouseMove={handleMouseMove}
            onMouseEnter={handleMouseEnter}
            onMouseLeave={handleMouseLeave}
            className={cn(
                'relative overflow-hidden rounded-xl border border-neutral-200 bg-white text-neutral-900 shadow-sm dark:border-neutral-800 dark:bg-neutral-900 dark:text-neutral-50',
                className
            )}
            {...props}
        >
            <div
                className="pointer-events-none absolute -inset-px transition duration-300"
                style={{
                    opacity,
                    background: `radial-gradient(600px circle at ${position.x}px ${position.y}px, ${spotlightColor}, transparent 40%)`,
                }}
            />
            <div className="relative h-full">{children}</div>
        </div>
    );
}

// frontend/src/app/shared/components/spotlight-card/spotlight-card.component.ts
import {
  Component,
  ElementRef,
  HostListener,
  ViewChild,
  AfterViewInit,
  ChangeDetectorRef,
  ChangeDetectionStrategy,
  NgZone,
  inject,
} from '@angular/core';

@Component({
  selector: 'app-spotlight-card',
  standalone: true,
  imports: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      #card
      class="group relative overflow-hidden rounded-2xl border border-slate-200/70 bg-white p-8 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-primary-400/60 hover:shadow-lg dark:border-white/10 dark:bg-slate-950"
    >
      <!-- Spotlight Effect -->
      <div
        #spotlight
        class="pointer-events-none absolute -inset-px opacity-0 transition-opacity duration-500 group-hover:opacity-100"
        [style.background]="spotlightGradient"
      ></div>

      <!-- Content -->
      <div class="relative z-10">
        <ng-content></ng-content>
      </div>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
      }
    `,
  ],
})
export class SpotlightCardComponent implements AfterViewInit {
  @ViewChild('card', { static: false }) card!: ElementRef<HTMLDivElement>;
  @ViewChild('spotlight', { static: false }) spotlight!: ElementRef<HTMLDivElement>;

  spotlightGradient = 'transparent';

  private readonly cdr = inject(ChangeDetectorRef);
  private readonly ngZone = inject(NgZone);

  ngAfterViewInit(): void {
    // Run outside Angular to avoid NG0100 error
    this.ngZone.runOutsideAngular(() => {
      setTimeout(() => {
        this.spotlightGradient = 'transparent';
      }, 0);
    });
  }

  @HostListener('mousemove', ['$event'])
  onMouseMove(event: MouseEvent): void {
    this.updateSpotlight(event);
  }

  private updateSpotlight(event: MouseEvent): void {
    if (!this.card || !this.spotlight) return;

    const rect = this.card.nativeElement.getBoundingClientRect();
    const x = event.clientX - rect.left;
    const y = event.clientY - rect.top;

    this.spotlightGradient = `
      radial-gradient(
        540px circle at ${x}px ${y}px,
        rgba(59, 130, 246, 0.18),
        transparent 45%
      )
    `;

    this.cdr.markForCheck();
  }
}
