// apps/web/src/app/shared/components/spotlight-card/spotlight-card.component.ts
import { Component, ElementRef, HostListener, ViewChild, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-spotlight-card',
    standalone: true,
    imports: [CommonModule],
    template: `
    <div 
      #card
      class="relative overflow-hidden rounded-2xl bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-800 border border-gray-200 dark:border-gray-700 p-8 transition-all duration-300 hover:border-cermont-primary-500 dark:hover:border-cermont-primary-500 group"
    >
      <!-- Spotlight Effect -->
      <div 
        #spotlight
        class="pointer-events-none absolute -inset-px opacity-0 group-hover:opacity-100 transition-opacity duration-500"
        [style.background]="spotlightGradient"
      ></div>

      <!-- Content -->
      <div class="relative z-10">
        <ng-content></ng-content>
      </div>
    </div>
  `,
    styles: [`
    :host {
      display: block;
    }
  `]
})
export class SpotlightCardComponent implements AfterViewInit {
    @ViewChild('card', { static: false }) card!: ElementRef<HTMLDivElement>;
    @ViewChild('spotlight', { static: false }) spotlight!: ElementRef<HTMLDivElement>;

    spotlightGradient = '';

    ngAfterViewInit(): void {
        this.updateSpotlight({ clientX: 0, clientY: 0 } as MouseEvent);
    }

    @HostListener('mousemove', ['$event'])
    onMouseMove(event: MouseEvent): void {
        this.updateSpotlight(event);
    }

    private updateSpotlight(event: MouseEvent): void {
        if (!this.card || !this.spotlight) return;

        const rect = this.card.nativeElement.getBoundingClientRect();
        const x = event.clientX - rect.left;
        const y = event.clientY - rect.top;

        this.spotlightGradient = `
      radial-gradient(
        600px circle at ${x}px ${y}px,
        rgba(0, 191, 255, 0.15),
        transparent 40%
      )
    `;
    }
}

// apps/web/src/components/ui/SpotlightCard.tsx
'use client';

import { useRef, useState, useEffect } from 'react';
import { cn } from '@/lib/utils';

interface SpotlightCardProps extends React.HTMLAttributes<HTMLDivElement> {
    children: ReactNode;
    spotlightColor?: string;
    className?: string;
}

import { type ReactNode } from 'react';

export function SpotlightCard({
    children,
    className = '',
    spotlightColor = 'rgba(255, 255, 255, 0.1)',
    ...props
}: SpotlightCardProps) {
    const divRef = useRef<HTMLDivElement>(null);
    const [position, setPosition] = useState({ x: 0, y: 0 });
    const [opacity, setOpacity] = useState(0);

    const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
        if (!divRef.current) return;

        const div = divRef.current;
        const rect = div.getBoundingClientRect();

        setPosition({ x: e.clientX - rect.left, y: e.clientY - rect.top });
    };

    const handleMouseEnter = () => {
        setOpacity(1);
    };

    const handleMouseLeave = () => {
        setOpacity(0);
    };

    return (
        <div
            ref={divRef}
            onMouseMove={handleMouseMove}
            onMouseEnter={handleMouseEnter}
            onMouseLeave={handleMouseLeave}
            className={cn(
                'relative overflow-hidden rounded-xl border border-neutral-200 bg-white text-neutral-900 shadow-sm dark:border-neutral-800 dark:bg-neutral-900 dark:text-neutral-50',
                className
            )}
            {...props}
        >
            <div
                className="pointer-events-none absolute -inset-px transition duration-300"
                style={{
                    opacity,
                    background: `radial-gradient(600px circle at ${position.x}px ${position.y}px, ${spotlightColor}, transparent 40%)`,
                }}
            />
            <div className="relative h-full">{children}</div>
        </div>
    );
}
