// frontend/src/app/shared/components/chat/asistente-ia.component.ts
/**
 * Asistente IA Component - Migrado de Next.js
 * @see apps/web-old/src/components/chat/AsistenteIA.tsx
 *
 * Componente de chat con asistente inteligente para CERMONT
 * Incluye sugerencias rápidas, respuestas predefinidas y diseño moderno
 */

import { Component, OnInit, signal, inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { FormsModule } from '@angular/forms';

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
  metadata?: {
    type?: 'text' | 'suggestion' | 'action' | 'error';
    data?: unknown;
  };
}

interface QuickSuggestion {
  icon: string;
  text: string;
}

@Component({
  selector: 'app-asistente-ia',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './asistente-ia.component.html',
  styleUrl: './asistente-ia.component.css',
})
export class AsistenteIAComponent implements OnInit {
  private readonly platformId = inject(PLATFORM_ID);

  // Estado del componente
  isOpen = signal(false);
  isMinimized = signal(false);
  messages = signal<ChatMessage[]>([
    {
      id: '1',
      role: 'assistant',
      content: '¡Hola! 👋 Soy el asistente virtual de CERMONT. ¿En qué puedo ayudarte hoy?',
      timestamp: new Date(),
    },
  ]);
  inputValue = signal('');
  isTyping = signal(false);

  // Sugerencias rápidas
  readonly quickSuggestions: QuickSuggestion[] = [
    { icon: '📄', text: '¿Cómo crear una orden?' },
    { icon: '📅', text: 'Mostrar órdenes de hoy' },
    { icon: '🔧', text: 'Procedimiento de mantenimiento' },
    { icon: '❓', text: 'Ayuda con formularios' },
  ];

  // Respuestas predefinidas
  private readonly predefinedResponses: Record<string, string> = {
    'crear orden': `Para crear una nueva orden de trabajo:

1. Ve a **Dashboard > Órdenes > Nueva Orden**
2. Completa los datos del cliente y ubicación
3. Selecciona el tipo de trabajo (IT, MNT, SC, GEN)
4. Asigna técnicos disponibles
5. Define las fechas estimadas
6. Guarda la orden

¿Necesitas ayuda con algún paso específico?`,

    'ordenes hoy': `📋 **Resumen de órdenes para hoy:**

• **OT-2024-001** - Mantenimiento Torre T-15 (En ejecución)
• **OT-2024-002** - Inspección línea de vida (Pendiente)
• **OT-2024-003** - Instalación CCTV (Programada 14:00)

Para ver detalles, haz clic en cualquier orden o ve a **Dashboard > Órdenes**.`,

    mantenimiento: `📖 **Procedimiento estándar de mantenimiento:**

**Antes de iniciar:**
1. Revisar orden de trabajo y alcance
2. Verificar permisos y documentación
3. Inspeccionar EPP y herramientas

**Durante la ejecución:**
1. Seguir checklist OPE-001
2. Documentar con fotos cada paso
3. Registrar materiales utilizados

**Al finalizar:**
1. Completar formulario de cierre
2. Subir evidencias fotográficas
3. Obtener firma del supervisor

¿Quieres ver un formulario específico?`,

    formularios: `📝 **Formularios disponibles en el sistema:**

• **OPE-001** - Planeación de Obra
• **OPE-002** - Ejecución de Trabajo
• **OPE-003** - Cierre Administrativo
• **OPE-004** - Inspección de EPP
• **OPE-005** - Reporte de Incidentes
• **OPE-006** - Inspección Línea de Vida
• **OPE-007** - Control de Materiales

Para acceder, ve a **Dashboard > Formularios** o usa el botón "Nuevo" en cada módulo.`,

    ayuda: `🤖 **¡Hola! Soy tu asistente CERMONT.**

Puedo ayudarte con:

✅ Crear y gestionar órdenes de trabajo
✅ Llenar formularios operativos
✅ Consultar procedimientos
✅ Ver estado de técnicos y equipos
✅ Generar reportes

**Comandos rápidos:**
• "Crear orden" - Iniciar nueva OT
• "Órdenes de hoy" - Ver agenda
• "Mantenimiento" - Procedimientos
• "Reportes" - Generar informes

¿En qué puedo ayudarte?`,

    default: `Entiendo tu consulta. Déjame ayudarte.

Para asistencia más específica, puedes:
1. Reformular tu pregunta
2. Usar los botones de sugerencias
3. Contactar soporte técnico

¿Hay algo más en lo que pueda ayudarte?`,
  };

  ngOnInit(): void {
    // Auto-scroll al nuevo mensaje
    if (isPlatformBrowser(this.platformId)) {
      setTimeout(() => this.scrollToBottom(), 100);
    }
  }

  /**
   * Generar respuesta basada en el mensaje del usuario
   */
  private generateResponse(userMessage: string): string {
    const lowerMessage = userMessage.toLowerCase();

    if (lowerMessage.includes('crear') && lowerMessage.includes('orden')) {
      return this.predefinedResponses['crear orden'];
    }
    if (
      lowerMessage.includes('orden') &&
      (lowerMessage.includes('hoy') || lowerMessage.includes('día'))
    ) {
      return this.predefinedResponses['ordenes hoy'];
    }
    if (lowerMessage.includes('mantenimiento') || lowerMessage.includes('procedimiento')) {
      return this.predefinedResponses['mantenimiento'];
    }
    if (lowerMessage.includes('formulario') || lowerMessage.includes('formato')) {
      return this.predefinedResponses['formularios'];
    }
    if (
      lowerMessage.includes('ayuda') ||
      lowerMessage.includes('hola') ||
      lowerMessage.includes('qué puedes')
    ) {
      return this.predefinedResponses['ayuda'];
    }

    return this.predefinedResponses['default'];
  }

  /**
   * Enviar mensaje
   */
  async sendMessage(content?: string): Promise<void> {
    const messageContent = content || this.inputValue().trim();
    if (!messageContent) return;

    // Mensaje del usuario
    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: messageContent,
      timestamp: new Date(),
    };

    this.messages.update(msgs => [...msgs, userMessage]);
    this.inputValue.set('');
    this.isTyping.set(true);

    // Simular delay de respuesta
    await new Promise(resolve => setTimeout(resolve, 800 + Math.random() * 1200));

    // Respuesta del asistente
    const response = this.generateResponse(messageContent);
    const assistantMessage: ChatMessage = {
      id: (Date.now() + 1).toString(),
      role: 'assistant',
      content: response,
      timestamp: new Date(),
    };

    this.messages.update(msgs => [...msgs, assistantMessage]);
    this.isTyping.set(false);
    this.scrollToBottom();
  }

  /**
   * Manejar sugerencia rápida
   */
  handleSuggestion(suggestion: string): void {
    this.sendMessage(suggestion);
  }

  /**
   * Manejar tecla Enter
   */
  handleKeyPress(event: KeyboardEvent): void {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      this.sendMessage();
    }
  }

  /**
   * Abrir chat
   */
  openChat(): void {
    this.isOpen.set(true);
    this.isMinimized.set(false);
  }

  /**
   * Cerrar chat
   */
  closeChat(): void {
    this.isOpen.set(false);
  }

  /**
   * Minimizar chat
   */
  minimizeChat(): void {
    this.isMinimized.set(true);
  }

  /**
   * Maximizar chat
   */
  maximizeChat(): void {
    this.isMinimized.set(false);
  }

  /**
   * Scroll al final de los mensajes
   */
  private scrollToBottom(): void {
    if (!isPlatformBrowser(this.platformId)) return;

    setTimeout(() => {
      const messagesContainer = document.getElementById('messages-container');
      if (messagesContainer) {
        messagesContainer.scrollTop = messagesContainer.scrollHeight;
      }
    }, 100);
  }

  /**
   * Formatear contenido del mensaje (markdown básico)
   */
  formatMessage(content: string): string {
    return content.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>');
  }

  /**
   * Formatear hora
   */
  formatTime(date: Date): string {
    return date.toLocaleTimeString('es-CO', {
      hour: '2-digit',
      minute: '2-digit',
    });
  }
}

<!-- Botón flotante cuando está cerrado -->
@if (!isOpen()) {
  <button
    (click)="openChat()"
    class="fixed bottom-24 right-4 md:bottom-6 md:right-6 w-14 h-14 bg-gradient-to-r from-blue-600 to-blue-700 text-white rounded-full shadow-lg hover:shadow-xl transition-all duration-300 flex items-center justify-center z-40 group"
    aria-label="Abrir asistente IA"
  >
    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"
      />
    </svg>
    <span
      class="absolute -top-2 -right-2 w-5 h-5 bg-green-500 rounded-full flex items-center justify-center"
    >
      <span class="w-2 h-2 bg-white rounded-full animate-pulse"></span>
    </span>
    <span
      class="absolute right-full mr-3 px-3 py-1 bg-gray-900 text-white text-sm rounded-lg opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap"
    >
      Asistente IA
    </span>
  </button>
}

<!-- Chat minimizado -->
@if (isOpen() && isMinimized()) {
  <div class="fixed bottom-24 right-4 md:bottom-6 md:right-6 z-40">
    <div class="bg-white dark:bg-gray-800 rounded-xl shadow-2xl w-72 border">
      <div
        class="flex items-center justify-between p-3 bg-gradient-to-r from-blue-600 to-blue-700 rounded-t-xl"
      >
        <div class="flex items-center gap-2 text-white">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
            />
          </svg>
          <span class="font-medium text-sm">Asistente CERMONT</span>
        </div>
        <div class="flex items-center gap-1">
          <button (click)="maximizeChat()" class="p-1 hover:bg-white/20 rounded">
            <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4"
              />
            </svg>
          </button>
          <button (click)="closeChat()" class="p-1 hover:bg-white/20 rounded">
            <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
}

<!-- Chat completo -->
@if (isOpen() && !isMinimized()) {
  <div class="fixed bottom-24 right-4 md:bottom-6 md:right-6 z-40 max-md:left-4 max-md:right-4">
    <div
      class="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full md:w-96 max-h-[calc(100vh-120px)] md:max-h-[600px] flex flex-col border overflow-hidden"
    >
      <!-- Header -->
      <div class="flex items-center justify-between p-4 bg-gradient-to-r from-blue-600 to-blue-700">
        <div class="flex items-center gap-3 text-white">
          <div class="relative">
            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
              />
            </svg>
            <span
              class="absolute -bottom-1 -right-1 w-3 h-3 bg-green-400 rounded-full border-2 border-blue-600"
            ></span>
          </div>
          <div>
            <h3 class="font-semibold">Asistente CERMONT</h3>
            <p class="text-xs text-blue-100">En línea • IA asistente</p>
          </div>
        </div>
        <div class="flex items-center gap-1">
          <button (click)="minimizeChat()" class="p-2 hover:bg-white/20 rounded-lg transition">
            <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H4" />
            </svg>
          </button>
          <button (click)="closeChat()" class="p-2 hover:bg-white/20 rounded-lg transition">
            <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>
      </div>

      <!-- Sugerencias rápidas -->
      <div class="p-3 border-b bg-gray-50 dark:bg-gray-900">
        <p class="text-xs text-gray-500 mb-2">Sugerencias rápidas:</p>
        <div class="flex flex-wrap gap-2">
          @for (sug of quickSuggestions; track sug.text) {
            <button
              (click)="handleSuggestion(sug.text)"
              class="flex items-center gap-1.5 px-2.5 py-1 bg-white dark:bg-gray-800 border rounded-full text-xs hover:bg-blue-50 hover:border-blue-300 transition"
            >
              <span>{{ sug.icon }}</span>
              <span class="truncate max-w-[120px]">{{ sug.text }}</span>
            </button>
          }
        </div>
      </div>

      <!-- Mensajes -->
      <div id="messages-container" class="flex-1 overflow-y-auto p-4 space-y-4 max-h-80">
        @for (message of messages(); track message.id) {
          <div class="flex gap-3" [class.flex-row-reverse]="message.role === 'user'">
            <!-- Avatar -->
            <div
              class="shrink-0 w-8 h-8 rounded-full flex items-center justify-center"
              [class.bg-blue-600]="message.role === 'user'"
              [class.bg-gradient-to-br]="message.role === 'assistant'"
              [class.from-purple-500]="message.role === 'assistant'"
              [class.to-blue-500]="message.role === 'assistant'"
              [class.text-white]="true"
            >
              @if (message.role === 'user') {
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                  />
                </svg>
              } @else {
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
                  />
                </svg>
              }
            </div>

            <!-- Mensaje -->
            <div class="max-w-[75%]" [class.text-right]="message.role === 'user'">
              <div
                class="rounded-2xl px-4 py-2.5"
                [class.bg-blue-600]="message.role === 'user'"
                [class.text-white]="message.role === 'user'"
                [class.rounded-br-md]="message.role === 'user'"
                [class.bg-gray-100]="message.role === 'assistant'"
                [class.dark:bg-gray-700]="message.role === 'assistant'"
                [class.text-gray-800]="message.role === 'assistant'"
                [class.dark:text-gray-200]="message.role === 'assistant'"
                [class.rounded-bl-md]="message.role === 'assistant'"
              >
                <div
                  class="text-sm whitespace-pre-wrap"
                  [innerHTML]="formatMessage(message.content)"
                ></div>
              </div>
              <p class="text-xs text-gray-400 mt-1 px-2">{{ formatTime(message.timestamp) }}</p>
            </div>
          </div>
        }

        <!-- Indicador de escritura -->
        @if (isTyping()) {
          <div class="flex gap-3">
            <div
              class="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center"
            >
              <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
                />
              </svg>
            </div>
            <div class="bg-gray-100 dark:bg-gray-700 rounded-2xl rounded-bl-md px-4 py-3">
              <div class="flex gap-1">
                <span
                  class="w-2 h-2 bg-gray-400 rounded-full animate-bounce"
                  style="animation-delay: 0ms"
                ></span>
                <span
                  class="w-2 h-2 bg-gray-400 rounded-full animate-bounce"
                  style="animation-delay: 150ms"
                ></span>
                <span
                  class="w-2 h-2 bg-gray-400 rounded-full animate-bounce"
                  style="animation-delay: 300ms"
                ></span>
              </div>
            </div>
          </div>
        }
      </div>

      <!-- Input -->
      <div class="p-4 border-t bg-white dark:bg-gray-800">
        <div class="flex gap-2">
          <input
            type="text"
            [(ngModel)]="inputValue"
            (keydown)="handleKeyPress($event)"
            placeholder="Escribe tu mensaje..."
            class="flex-1 px-4 py-2.5 border rounded-xl text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600"
            [disabled]="isTyping()"
          />
          <button
            (click)="sendMessage()"
            [disabled]="!inputValue().trim() || isTyping()"
            class="px-4 py-2.5 bg-blue-600 text-white rounded-xl hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
          >
            @if (isTyping()) {
              <svg
                class="w-5 h-5 animate-spin"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                />
              </svg>
            } @else {
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
                />
              </svg>
            }
          </button>
        </div>
        <p class="text-xs text-gray-400 text-center mt-2">
          Powered by CERMONT IA • Respuestas simuladas
        </p>
      </div>
    </div>
  </div>
}

// apps/web/src/components/chat/AsistenteIA.tsx
'use client';

import React, { useState, useRef, useEffect, useCallback } from 'react';
import {
  MessageSquare,
  Send,
  X,
  Minimize2,
  Maximize2,
  Bot,
  User,
  Loader2,
  Sparkles,
  HelpCircle,
  FileText,
  Calendar,
  Wrench
} from 'lucide-react';

// ============================================
// TYPES
// ============================================

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
  metadata?: {
    type?: 'text' | 'suggestion' | 'action' | 'error';
    actions?: ChatAction[];
    data?: any;
  };
}

export interface ChatAction {
  label: string;
  action: string;
  params?: Record<string, any>;
  icon?: React.ReactNode;
}

interface AsistenteIAProps {
  onAction?: (action: string, params?: Record<string, any>) => void;
  contextData?: {
    currentPage?: string;
    ordenActiva?: string;
    usuario?: string;
  };
  className?: string;
}

// ============================================
// PREDEFINED RESPONSES (Simulación local)
// En producción, esto se conectaría a OpenAI/Claude API
// ============================================

const SUGERENCIAS_RAPIDAS = [
  { icon: <FileText className="w-4 h-4" />, text: '¿Cómo crear una orden?' },
  { icon: <Calendar className="w-4 h-4" />, text: 'Mostrar órdenes de hoy' },
  { icon: <Wrench className="w-4 h-4" />, text: 'Procedimiento de mantenimiento' },
  { icon: <HelpCircle className="w-4 h-4" />, text: 'Ayuda con formularios' },
];

const RESPUESTAS_PREDEFINIDAS: Record<string, string> = {
  'crear orden': `Para crear una nueva orden de trabajo:

1. Ve a **Dashboard > Órdenes > Nueva Orden**
2. Completa los datos del cliente y ubicación
3. Selecciona el tipo de trabajo (IT, MNT, SC, GEN)
4. Asigna técnicos disponibles
5. Define las fechas estimadas
6. Guarda la orden

¿Necesitas ayuda con algún paso específico?`,

  'ordenes hoy': `📋 **Resumen de órdenes para hoy:**

• **OT-2024-001** - Mantenimiento Torre T-15 (En ejecución)
• **OT-2024-002** - Inspección línea de vida (Pendiente)
• **OT-2024-003** - Instalación CCTV (Programada 14:00)

Para ver detalles, haz clic en cualquier orden o ve a **Dashboard > Órdenes**.`,

  'mantenimiento': `📖 **Procedimiento estándar de mantenimiento:**

**Antes de iniciar:**
1. Revisar orden de trabajo y alcance
2. Verificar permisos y documentación
3. Inspeccionar EPP y herramientas

**Durante la ejecución:**
1. Seguir checklist OPE-001
2. Documentar con fotos cada paso
3. Registrar materiales utilizados

**Al finalizar:**
1. Completar formulario de cierre
2. Subir evidencias fotográficas
3. Obtener firma del supervisor

¿Quieres ver un formulario específico?`,

  'formularios': `📝 **Formularios disponibles en el sistema:**

• **OPE-001** - Planeación de Obra
• **OPE-002** - Ejecución de Trabajo
• **OPE-003** - Cierre Administrativo
• **OPE-004** - Inspección de EPP
• **OPE-005** - Reporte de Incidentes
• **OPE-006** - Inspección Línea de Vida
• **OPE-007** - Control de Materiales

Para acceder, ve a **Dashboard > Formularios** o usa el botón "Nuevo" en cada módulo.`,

  'ayuda': `🤖 **¡Hola! Soy tu asistente CERMONT.**

Puedo ayudarte con:

✅ Crear y gestionar órdenes de trabajo
✅ Llenar formularios operativos
✅ Consultar procedimientos
✅ Ver estado de técnicos y equipos
✅ Generar reportes

**Comandos rápidos:**
• "Crear orden" - Iniciar nueva OT
• "Órdenes de hoy" - Ver agenda
• "Mantenimiento" - Procedimientos
• "Reportes" - Generar informes

¿En qué puedo ayudarte?`,

  default: `Entiendo tu consulta. Déjame ayudarte.

Para asistencia más específica, puedes:
1. Reformular tu pregunta
2. Usar los botones de sugerencias
3. Contactar soporte técnico

¿Hay algo más en lo que pueda ayudarte?`,
};

// ============================================
// COMPONENT
// ============================================

export function AsistenteIA({ onAction: _onAction, contextData: _contextData, className = '' }: AsistenteIAProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isMinimized, setIsMinimized] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: '1',
      role: 'assistant',
      content: '¡Hola! 👋 Soy el asistente virtual de CERMONT. ¿En qué puedo ayudarte hoy?',
      timestamp: new Date(),
    },
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Auto-scroll al nuevo mensaje
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Focus input cuando se abre
  useEffect(() => {
    if (isOpen && !isMinimized) {
      inputRef.current?.focus();
    }
  }, [isOpen, isMinimized]);

  // Generar respuesta (simulada)
  const generateResponse = useCallback((userMessage: string): string => {
    const lowerMessage = userMessage.toLowerCase();

    if (lowerMessage.includes('crear') && lowerMessage.includes('orden')) {
      return RESPUESTAS_PREDEFINIDAS['crear orden'];
    }
    if (lowerMessage.includes('orden') && (lowerMessage.includes('hoy') || lowerMessage.includes('día'))) {
      return RESPUESTAS_PREDEFINIDAS['ordenes hoy'];
    }
    if (lowerMessage.includes('mantenimiento') || lowerMessage.includes('procedimiento')) {
      return RESPUESTAS_PREDEFINIDAS['mantenimiento'];
    }
    if (lowerMessage.includes('formulario') || lowerMessage.includes('formato')) {
      return RESPUESTAS_PREDEFINIDAS['formularios'];
    }
    if (lowerMessage.includes('ayuda') || lowerMessage.includes('hola') || lowerMessage.includes('qué puedes')) {
      return RESPUESTAS_PREDEFINIDAS['ayuda'];
    }

    return RESPUESTAS_PREDEFINIDAS['default'];
  }, []);

  // Enviar mensaje
  const sendMessage = useCallback(async (content: string) => {
    if (!content.trim()) return;

    // Mensaje del usuario
    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: content.trim(),
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsTyping(true);

    // Simular delay de respuesta
    await new Promise(resolve => setTimeout(resolve, 800 + Math.random() * 1200));

    // Respuesta del asistente
    const response = generateResponse(content);
    const assistantMessage: ChatMessage = {
      id: (Date.now() + 1).toString(),
      role: 'assistant',
      content: response,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, assistantMessage]);
    setIsTyping(false);
  }, [generateResponse]);

  // Manejar sugerencia rápida
  const handleSuggestion = (suggestion: string) => {
    sendMessage(suggestion);
  };

  // Manejar Enter
  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage(inputValue);
    }
  };

  // Botón flotante
  if (!isOpen) {
    return (
      <button
        onClick={() => setIsOpen(true)}
        className={`fixed bottom-6 right-6 w-14 h-14 bg-gradient-to-r from-blue-600 to-blue-700 text-white rounded-full shadow-lg hover:shadow-xl transition-all duration-300 flex items-center justify-center z-50 group ${className}`}
      >
        <MessageSquare className="w-6 h-6" />
        <span className="absolute -top-2 -right-2 w-5 h-5 bg-green-500 rounded-full flex items-center justify-center">
          <span className="w-2 h-2 bg-white rounded-full animate-pulse" />
        </span>
        <span className="absolute right-full mr-3 px-3 py-1 bg-gray-900 text-white text-sm rounded-lg opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
          Asistente IA
        </span>
      </button>
    );
  }

  // Chat minimizado
  if (isMinimized) {
    return (
      <div className="fixed bottom-6 right-6 z-50">
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-2xl w-72 border">
          <div className="flex items-center justify-between p-3 bg-gradient-to-r from-blue-600 to-blue-700 rounded-t-xl">
            <div className="flex items-center gap-2 text-white">
              <Bot className="w-5 h-5" />
              <span className="font-medium text-sm">Asistente CERMONT</span>
            </div>
            <div className="flex items-center gap-1">
              <button
                onClick={() => setIsMinimized(false)}
                className="p-1 hover:bg-white/20 rounded"
              >
                <Maximize2 className="w-4 h-4 text-white" />
              </button>
              <button
                onClick={() => setIsOpen(false)}
                className="p-1 hover:bg-white/20 rounded"
              >
                <X className="w-4 h-4 text-white" />
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Chat completo
  return (
    <div className="fixed bottom-6 right-6 z-50">
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-96 max-h-[600px] flex flex-col border overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-4 bg-gradient-to-r from-blue-600 to-blue-700">
          <div className="flex items-center gap-3 text-white">
            <div className="relative">
              <Bot className="w-8 h-8" />
              <span className="absolute -bottom-1 -right-1 w-3 h-3 bg-green-400 rounded-full border-2 border-blue-600" />
            </div>
            <div>
              <h3 className="font-semibold">Asistente CERMONT</h3>
              <p className="text-xs text-blue-100">En línea • IA asistente</p>
            </div>
          </div>
          <div className="flex items-center gap-1">
            <button
              onClick={() => setIsMinimized(true)}
              className="p-2 hover:bg-white/20 rounded-lg transition"
            >
              <Minimize2 className="w-4 h-4 text-white" />
            </button>
            <button
              onClick={() => setIsOpen(false)}
              className="p-2 hover:bg-white/20 rounded-lg transition"
            >
              <X className="w-4 h-4 text-white" />
            </button>
          </div>
        </div>

        {/* Sugerencias rápidas */}
        <div className="p-3 border-b bg-gray-50 dark:bg-gray-900">
          <p className="text-xs text-gray-500 mb-2">Sugerencias rápidas:</p>
          <div className="flex flex-wrap gap-2">
            {SUGERENCIAS_RAPIDAS.map((sug, i) => (
              <button
                key={i}
                onClick={() => handleSuggestion(sug.text)}
                className="flex items-center gap-1.5 px-2.5 py-1 bg-white dark:bg-gray-800 border rounded-full text-xs hover:bg-blue-50 hover:border-blue-300 transition"
              >
                {sug.icon}
                <span className="truncate max-w-[120px]">{sug.text}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Mensajes */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4 max-h-80">
          {messages.map((message) => (
            <div
              key={message.id}
              className={`flex gap-3 ${message.role === 'user' ? 'flex-row-reverse' : ''}`}
            >
              {/* Avatar */}
              <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center ${
                message.role === 'user' 
                  ? 'bg-blue-600 text-white' 
                  : 'bg-gradient-to-br from-purple-500 to-blue-500 text-white'
              }`}>
                {message.role === 'user' ? (
                  <User className="w-4 h-4" />
                ) : (
                  <Sparkles className="w-4 h-4" />
                )}
              </div>

              {/* Mensaje */}
              <div className={`max-w-[75%] ${message.role === 'user' ? 'text-right' : ''}`}>
                <div className={`rounded-2xl px-4 py-2.5 ${
                  message.role === 'user'
                    ? 'bg-blue-600 text-white rounded-br-md'
                    : 'bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-bl-md'
                }`}>
                  <div 
                    className="text-sm whitespace-pre-wrap"
                    dangerouslySetInnerHTML={{ 
                      __html: message.content
                        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                        .replace(/\n/g, '<br>')
                    }} 
                  />
                </div>
                <p className="text-xs text-gray-400 mt-1 px-2">
                  {message.timestamp.toLocaleTimeString('es-CO', { 
                    hour: '2-digit', 
                    minute: '2-digit' 
                  })}
                </p>
              </div>
            </div>
          ))}

          {/* Typing indicator */}
          {isTyping && (
            <div className="flex gap-3">
              <div className="w-8 h-8 rounded-full bg-gradient-to-br from-purple-500 to-blue-500 flex items-center justify-center">
                <Sparkles className="w-4 h-4 text-white" />
              </div>
              <div className="bg-gray-100 dark:bg-gray-700 rounded-2xl rounded-bl-md px-4 py-3">
                <div className="flex gap-1">
                  <span className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                  <span className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                  <span className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                </div>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <div className="p-4 border-t bg-white dark:bg-gray-800">
          <div className="flex gap-2">
            <input
              ref={inputRef}
              type="text"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyPress={handleKeyPress}
              placeholder="Escribe tu mensaje..."
              className="flex-1 px-4 py-2.5 border rounded-xl text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600"
              disabled={isTyping}
            />
            <button
              onClick={() => sendMessage(inputValue)}
              disabled={!inputValue.trim() || isTyping}
              className="px-4 py-2.5 bg-blue-600 text-white rounded-xl hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
            >
              {isTyping ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <Send className="w-5 h-5" />
              )}
            </button>
          </div>
          <p className="text-xs text-gray-400 text-center mt-2">
            Powered by CERMONT IA • Respuestas simuladas
          </p>
        </div>
      </div>
    </div>
  );
}

export default AsistenteIA;
