// apps/web/src/components/landing/LandingHeader.tsx
'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useState, useEffect } from 'react';
import { ThemeToggleButton } from '@/components/common/ThemeToggleButton';

export default function LandingHeader() {
    const [isScrolled, setIsScrolled] = useState(false);
    const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

    useEffect(() => {
        const handleScroll = () => {
            setIsScrolled(window.scrollY > 20);
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    return (
        <header
            className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${isScrolled
                ? 'glass shadow-md py-3'
                : 'bg-transparent py-5'
                }`}
        >
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex items-center justify-between">
                    {/* Logo */}
                    <Link href="/" className="flex items-center gap-3 group">
                        <div className="relative w-10 h-10 transition-transform duration-300 group-hover:scale-110">
                            <Image
                                src="/logo.svg"
                                alt="Cermont Logo"
                                fill
                                className="object-contain"
                            />
                        </div>
                        <span className="text-xl font-bold text-gray-900 dark:text-white">
                            CERMONT
                        </span>
                    </Link>

                    {/* Desktop Navigation */}
                    <nav className="hidden md:flex items-center gap-8">
                        <a
                            href="#servicios"
                            className="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
                        >
                            Servicios
                        </a>
                        <a
                            href="#nosotros"
                            className="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
                        >
                            Nosotros
                        </a>
                        <a
                            href="#contacto"
                            className="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
                        >
                            Contacto
                        </a>
                    </nav>

                    {/* CTA Buttons */}
                    <div className="hidden md:flex items-center gap-4">
                        <ThemeToggleButton />
                        <Link
                            href="/login"
                            className="text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white transition-colors"
                        >
                            Iniciar Sesión
                        </Link>
                        <Link
                            href="/register"
                            className="btn-primary text-sm"
                        >
                            Registrarse
                        </Link>
                    </div>

                    {/* Mobile Menu Button */}
                    <div className="flex items-center gap-2 md:hidden">
                        <ThemeToggleButton />
                        <button
                            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
                            className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                            aria-label="Toggle menu"
                        >
                            <svg
                                className="w-6 h-6 text-gray-700 dark:text-gray-300"
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                            >
                                {isMobileMenuOpen ? (
                                    <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth={2}
                                        d="M6 18L18 6M6 6l12 12"
                                    />
                                ) : (
                                    <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth={2}
                                        d="M4 6h16M4 12h16M4 18h16"
                                    />
                                )}
                            </svg>
                        </button>
                    </div>
                </div>

                {/* Mobile Menu */}
                {isMobileMenuOpen && (
                    <div className="md:hidden mt-4 pb-4 border-t border-gray-200 dark:border-gray-700">
                        <nav className="flex flex-col gap-4 pt-4">
                            <a
                                href="#servicios"
                                className="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
                                onClick={() => setIsMobileMenuOpen(false)}
                            >
                                Servicios
                            </a>
                            <a
                                href="#nosotros"
                                className="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
                                onClick={() => setIsMobileMenuOpen(false)}
                            >
                                Nosotros
                            </a>
                            <a
                                href="#contacto"
                                className="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
                                onClick={() => setIsMobileMenuOpen(false)}
                            >
                                Contacto
                            </a>
                            <div className="flex flex-col gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">
                                <Link
                                    href="/login"
                                    className="btn-secondary text-center"
                                    onClick={() => setIsMobileMenuOpen(false)}
                                >
                                    Iniciar Sesión
                                </Link>
                                <Link
                                    href="/register"
                                    className="btn-primary text-center"
                                    onClick={() => setIsMobileMenuOpen(false)}
                                >
                                    Registrarse
                                </Link>
                            </div>
                        </nav>
                    </div>
                )}
            </div>
        </header>
    );
}

// apps/web/src/app/shared/components/landing/landing-header/landing-header.component.ts
/**
 * Landing Header Component - Migrado de Next.js
 * @see apps/web-old/src/components/landing/LandingHeader.tsx
 * 
 * Header con navegación sticky, menú móvil y toggle de tema
 */

import { Component, OnInit, OnDestroy, signal, inject, PLATFORM_ID, HostListener } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ThemeToggleButtonComponent } from '../../common/theme-toggle/theme-toggle-button.component';

@Component({
  selector: 'app-landing-header',
  standalone: true,
  imports: [CommonModule, RouterModule, ThemeToggleButtonComponent],
  templateUrl: './landing-header.component.html',
  styleUrl: './landing-header.component.css'
})
export class LandingHeaderComponent implements OnInit, OnDestroy {
  private readonly platformId = inject(PLATFORM_ID);
  
  isScrolled = signal(false);
  isMobileMenuOpen = signal(false);

  @HostListener('window:scroll', [])
  onWindowScroll(): void {
    if (!isPlatformBrowser(this.platformId)) return;
    this.isScrolled.set(window.scrollY > 20);
  }

  ngOnInit(): void {
    if (isPlatformBrowser(this.platformId)) {
      this.isScrolled.set(window.scrollY > 20);
    }
  }

  ngOnDestroy(): void {
    // Cleanup handled by HostListener
  }

  toggleMobileMenu(): void {
    this.isMobileMenuOpen.update(v => !v);
  }

  closeMobileMenu(): void {
    this.isMobileMenuOpen.set(false);
  }

  scrollToSection(sectionId: string): void {
    if (!isPlatformBrowser(this.platformId)) return;
    
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      this.closeMobileMenu();
    }
  }
}


<header
  class="fixed top-0 left-0 right-0 z-50 transition-all duration-300"
  [class.glass]="isScrolled()"
  [class.shadow-md]="isScrolled()"
  [class.py-3]="isScrolled()"
  [class.bg-transparent]="!isScrolled()"
  [class.py-5]="!isScrolled()">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between">
      <!-- Logo -->
      <a routerLink="/" class="flex items-center gap-3 group">
        <div class="relative w-10 h-10 transition-transform duration-300 group-hover:scale-110">
          <img src="/logo.svg" alt="Cermont Logo" class="w-full h-full object-contain" />
        </div>
        <span class="text-xl font-bold text-gray-900 dark:text-white">
          CERMONT
        </span>
      </a>

      <!-- Desktop Navigation -->
      <nav class="hidden md:flex items-center gap-8">
        <a
          (click)="scrollToSection('servicios'); $event.preventDefault()"
          class="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors cursor-pointer">
          Servicios
        </a>
        <a
          (click)="scrollToSection('nosotros'); $event.preventDefault()"
          class="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors cursor-pointer">
          Nosotros
        </a>
        <a
          (click)="scrollToSection('contacto'); $event.preventDefault()"
          class="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors cursor-pointer">
          Contacto
        </a>
      </nav>

      <!-- CTA Buttons -->
      <div class="hidden md:flex items-center gap-4">
        <app-theme-toggle-button />
        <a
          routerLink="/signin"
          class="text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white transition-colors">
          Iniciar Sesión
        </a>
        <a
          routerLink="/signup"
          class="btn-primary text-sm">
          Registrarse
        </a>
      </div>

      <!-- Mobile Menu Button -->
      <div class="flex items-center gap-2 md:hidden">
        <app-theme-toggle-button />
        <button
          (click)="toggleMobileMenu()"
          class="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          [attr.aria-label]="'Toggle menu'">
          @if (isMobileMenuOpen()) {
            <svg class="w-6 h-6 text-gray-700 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          } @else {
            <svg class="w-6 h-6 text-gray-700 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          }
        </button>
      </div>
    </div>

    <!-- Mobile Menu -->
    @if (isMobileMenuOpen()) {
      <div class="md:hidden mt-4 pb-4 border-t border-gray-200 dark:border-gray-700">
        <nav class="flex flex-col gap-4 pt-4">
          <a
            (click)="scrollToSection('servicios'); $event.preventDefault()"
            class="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors cursor-pointer">
            Servicios
          </a>
          <a
            (click)="scrollToSection('nosotros'); $event.preventDefault()"
            class="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors cursor-pointer">
            Nosotros
          </a>
          <a
            (click)="scrollToSection('contacto'); $event.preventDefault()"
            class="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors cursor-pointer">
            Contacto
          </a>
          <div class="flex flex-col gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">
            <a
              routerLink="/signin"
              (click)="closeMobileMenu()"
              class="btn-secondary text-center">
              Iniciar Sesión
            </a>
            <a
              routerLink="/signup"
              (click)="closeMobileMenu()"
              class="btn-primary text-center">
              Registrarse
            </a>
          </div>
        </nav>
      </div>
    }
  </div>
</header>
