// frontend/app/login/page.tsx
﻿// app/login/page.tsx
'use client';

// ============================================================================
// IMPORTS
// ============================================================================
import Image from 'next/image';
import Link from 'next/link';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useState } from 'react';
import { useAuth } from '@/lib/hooks/useAuth';

// Universal Components
import { AnimatedBackground } from '@/components/patterns/AnimatedBackground';
import { ErrorAlert } from '@/components/patterns/ErrorAlert';

// UI Components
import { ThemeToggle } from '@/components/ui/ThemeToggle';

// Icons
import { AlertCircle, ArrowRight, Mail, Lock, Shield, CheckCircle } from 'lucide-react';

// ============================================================================
// VALIDATION
// ============================================================================
const loginSchema = z.object({
  email: z.string().email('Email inválido'),
  password: z.string().min(8, 'Mínimo 8 caracteres'),
});

type LoginFormValues = z.infer<typeof loginSchema>;

// ============================================================================
// CONSTANTS
// ============================================================================
const TRUST_BADGES = [
  { text: 'ISO 9001 Certificado' },
  { text: 'RUC Vigente' },
  { text: '+15 Años de Experiencia' },
];

// ============================================================================
// MAIN COMPONENT
// ============================================================================
export default function LoginPage() {
  // ------------------------------------
  // Hooks & State
  // ------------------------------------
  const { login } = useAuth();
  const [serverError, setServerError] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
  });

  // ------------------------------------
  // Handlers
  // ------------------------------------
  const onSubmit = async (values: LoginFormValues) => {
    setServerError(null);
    try {
      await login(values);
    } catch (err: any) {
      setServerError(err?.response?.data?.detail ?? 'Credenciales incorrectas');
    }
  };

  // ============================================================================
  // RENDER
  // ============================================================================
  return (
    <AnimatedBackground className="flex items-center justify-center px-4">
      {/* Theme Toggle */}
      <div className="fixed right-6 top-6 z-50 animate-fade-in">
        <ThemeToggle />
      </div>

      {/* Login Container */}
      <div className="w-full max-w-md animate-slide-up">
        {/* ========================================
            SECTION: Logo
        ========================================== */}
        <div className="mb-10 flex justify-center">
          <Link href="/" className="group relative">
            {/* Glow Effect */}
            <div className="absolute -inset-4 animate-pulse rounded-full bg-gradient-to-r from-primary-500 to-secondary-500 opacity-20 blur-2xl transition-opacity group-hover:opacity-30"></div>

            {/* Logo Container */}
            <div className="relative flex h-32 w-32 items-center justify-center overflow-hidden rounded-full border-4 border-primary-500 bg-white shadow-2xl transition-transform group-hover:scale-105 dark:bg-neutral-900">
              <Image
                src="/logo-cermont.png"
                alt="CERMONT"
                width={100}
                height={100}
                className="object-contain p-4"
                priority
              />
            </div>

            {/* Badge */}
            <div className="absolute -right-2 -top-2 flex h-12 w-12 items-center justify-center rounded-full bg-gradient-to-br from-primary-500 to-primary-600 shadow-xl">
              <Shield className="h-6 w-6 text-white" />
            </div>
          </Link>
        </div>

        {/* ========================================
            SECTION: Header
        ========================================== */}
        <div className="mb-8 text-center">
          <h1 className="mb-2 text-4xl font-bold text-neutral-900 dark:text-neutral-50">
            CERMONT S.A.S
          </h1>
          <p className="text-lg font-medium text-neutral-600 dark:text-neutral-400">
            Sistema de Gestión ATG · Desde 2008
          </p>
        </div>

        {/* ========================================
            SECTION: Login Card
        ========================================== */}
        <div className="overflow-hidden rounded-3xl border-2 border-primary-200 bg-white/90 p-10 shadow-2xl backdrop-blur-xl dark:border-primary-900 dark:bg-neutral-900/90">
          <div className="mb-8">
            <h2 className="mb-2 text-2xl font-bold text-neutral-900 dark:text-neutral-50">
              Iniciar Sesión
            </h2>
            <p className="font-medium text-neutral-600 dark:text-neutral-400">
              Acceso seguro al sistema
            </p>
          </div>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            {/* Email Field */}
            <div>
              <label className="mb-3 block text-sm font-bold text-neutral-900 dark:text-neutral-50">
                Correo electrónico
              </label>
              <div className="relative">
                <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-4">
                  <Mail className="h-5 w-5 text-primary-500" />
                </div>
                <input
                  type="email"
                  placeholder="tu@cermont.com"
                  className={`h-14 w-full rounded-xl border-2 bg-white pl-12 pr-4 font-medium text-neutral-900 transition-all placeholder:text-neutral-400 focus:border-primary-500 focus:outline-none focus:ring-4 focus:ring-primary-100 dark:bg-neutral-800 dark:text-neutral-50 dark:placeholder:text-neutral-500 dark:focus:ring-primary-950 ${
                    errors.email
                      ? 'border-error-500 focus:border-error-500 focus:ring-error-100 dark:focus:ring-error-950'
                      : 'border-neutral-200 dark:border-neutral-700'
                  }`}
                  {...register('email')}
                />
              </div>
              {errors.email && (
                <p className="mt-2 flex items-center gap-1 text-sm font-bold text-error-600">
                  <AlertCircle className="h-4 w-4" />
                  {errors.email.message}
                </p>
              )}
            </div>

            {/* Password Field */}
            <div>
              <div className="mb-3 flex items-center justify-between">
                <label className="text-sm font-bold text-neutral-900 dark:text-neutral-50">
                  Contraseña
                </label>
                <Link
                  href="/forgot-password"
                  className="text-sm font-bold text-primary-600 transition-colors hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-300"
                >
                  ¿Olvidaste tu contraseña?
                </Link>
              </div>
              <div className="relative">
                <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-4">
                  <Lock className="h-5 w-5 text-primary-500" />
                </div>
                <input
                  type="password"
                  placeholder="••••••••"
                  className={`h-14 w-full rounded-xl border-2 bg-white pl-12 pr-4 font-medium text-neutral-900 transition-all placeholder:text-neutral-400 focus:border-primary-500 focus:outline-none focus:ring-4 focus:ring-primary-100 dark:bg-neutral-800 dark:text-neutral-50 dark:placeholder:text-neutral-500 dark:focus:ring-primary-950 ${
                    errors.password
                      ? 'border-error-500 focus:border-error-500 focus:ring-error-100 dark:focus:ring-error-950'
                      : 'border-neutral-200 dark:border-neutral-700'
                  }`}
                  {...register('password')}
                />
              </div>
              {errors.password && (
                <p className="mt-2 flex items-center gap-1 text-sm font-bold text-error-600">
                  <AlertCircle className="h-4 w-4" />
                  {errors.password.message}
                </p>
              )}
            </div>

            {/* Server Error Alert */}
            {serverError && (
              <ErrorAlert title="Error de autenticación" message={serverError} />
            )}

            {/* Submit Button */}
            <button
              type="submit"
              disabled={isSubmitting}
              className="group relative h-14 w-full overflow-hidden rounded-xl bg-gradient-to-r from-primary-600 to-primary-500 font-bold text-white shadow-2xl transition-all hover:scale-[1.02] hover:shadow-primary-500/50 disabled:opacity-50 disabled:hover:scale-100"
            >
              <div className="absolute inset-0 bg-gradient-to-r from-primary-500 to-primary-400 opacity-0 transition-opacity group-hover:opacity-100"></div>
              <span className="relative flex items-center justify-center gap-2 text-lg">
                {isSubmitting ? (
                  <>
                    <svg className="h-5 w-5 animate-spin" fill="none" viewBox="0 0 24 24">
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      />
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      />
                    </svg>
                    Ingresando...
                  </>
                ) : (
                  <>
                    Iniciar Sesión
                    <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" />
                  </>
                )}
              </span>
            </button>
          </form>

          {/* Footer Link */}
          <div className="mt-8 text-center">
            <p className="font-medium text-neutral-600 dark:text-neutral-400">
              ¿No tienes cuenta?{' '}
              <Link
                href="/request-access"
                className="font-bold text-primary-600 transition-colors hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-300"
              >
                Solicita acceso
              </Link>
            </p>
          </div>
        </div>

        {/* ========================================
            SECTION: Trust Badges
        ========================================== */}
        <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
          {TRUST_BADGES.map((badge) => (
            <div
              key={badge.text}
              className="flex items-center gap-2 rounded-full border-2 border-primary-200 bg-white/70 px-5 py-2 backdrop-blur-sm transition-all hover:border-primary-500 hover:bg-white dark:border-primary-900 dark:bg-neutral-900/70"
            >
              <div className="flex h-6 w-6 items-center justify-center rounded-full bg-success-50 dark:bg-success-950">
                <CheckCircle className="h-4 w-4 text-success-600 dark:text-success-400" />
              </div>
              <span className="text-sm font-bold text-neutral-700 dark:text-neutral-300">
                {badge.text}
              </span>
            </div>
          ))}
        </div>

        {/* Footer */}
        <p className="mt-6 text-center text-sm font-medium text-neutral-500 dark:text-neutral-400">
          © 2025 CERMONT S.A.S · Fundada en 2008 · Arauca, Colombia
        </p>
      </div>
    </AnimatedBackground>
  );
}

// apps/web/src/app/features/auth/components/login/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  private readonly fb = inject(FormBuilder);
  private readonly authService = inject(AuthService);
  private readonly router = inject(Router);

  form: FormGroup;
  loading = signal(false);
  error = signal<string | null>(null);
  showPassword = signal(false);

  constructor() {
    this.form = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(8)]],
      rememberMe: [false]
    });
  }

  onSubmit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.loading.set(true);
    this.error.set(null);

    const { email, password } = this.form.value;

    this.authService.login({ email, password }).subscribe({
      next: () => {
        this.router.navigate(['/dashboard']);
      },
      error: (err) => {
        console.error('Login error:', err);
        
        // Manejar diferentes tipos de errores
        if (err.status === 401) {
          this.error.set('Credenciales inválidas o usuario inactivo');
        } else if (err.status === 429) {
          this.error.set('Demasiados intentos. Por favor espera unos minutos');
        } else if (err.error?.message) {
          this.error.set(err.error.message);
        } else {
          this.error.set('Error al iniciar sesión. Intenta de nuevo');
        }
        
        this.loading.set(false);
      }
    });
  }

  togglePasswordVisibility(): void {
    this.showPassword.set(!this.showPassword());
  }

  hasError(field: string, error: string): boolean {
    const control = this.form.get(field);
    return !!(control && control.hasError(error) && control.touched);
  }
}


<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-cermont-primary-50 to-cermont-primary-100 dark:from-gray-900 dark:to-gray-800 px-4">
  <div class="max-w-md w-full">
    <!-- Logo y título -->
    <div class="text-center mb-8">
      <div class="inline-flex items-center justify-center w-16 h-16 bg-cermont-primary-500 rounded-full mb-4">
        <svg class="w-10 h-10 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/>
        </svg>
      </div>
      <h1 class="text-3xl font-bold text-gray-900 dark:text-white">Cermont</h1>
      <p class="text-gray-600 dark:text-gray-400 mt-2">Sistema de Gestión de Mantenimiento</p>
    </div>

    <!-- Card de login -->
    <div class="bg-white dark:bg-gray-800 rounded-2xl shadow-xl p-8">
      <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-6">Iniciar Sesión</h2>

      <!-- Mensaje de error -->
      @if (error()) {
        <div class="mb-6 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
          <div class="flex items-center">
            <svg class="w-5 h-5 text-red-600 dark:text-red-400 mr-3 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"/>
            </svg>
            <span class="text-sm text-red-800 dark:text-red-200">{{ error() }}</span>
          </div>
        </div>
      }

      <!-- Formulario -->
      <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-6">
        <!-- Email -->
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Email
          </label>
          <div class="relative">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                      d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207"/>
              </svg>
            </div>
            <input
              type="email"
              id="email"
              formControlName="email"
              class="input pl-10"
              [class.border-red-500]="hasError('email', 'required') || hasError('email', 'email')"
              placeholder="tu@email.com"
              autocomplete="email"
            />
          </div>
          @if (hasError('email', 'required')) {
            <p class="mt-1 text-sm text-red-600 dark:text-red-400">El email es requerido</p>
          }
          @if (hasError('email', 'email')) {
            <p class="mt-1 text-sm text-red-600 dark:text-red-400">Email inválido</p>
          }
        </div>

        <!-- Contraseña -->
        <div>
          <label for="password" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Contraseña
          </label>
          <div class="relative">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                      d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/>
              </svg>
            </div>
            <input
              [type]="showPassword() ? 'text' : 'password'"
              id="password"
              formControlName="password"
              class="input pl-10 pr-10"
              [class.border-red-500]="hasError('password', 'required') || hasError('password', 'minlength')"
              placeholder="••••••••"
              autocomplete="current-password"
            />
            <button
              type="button"
              (click)="togglePasswordVisibility()"
              class="absolute inset-y-0 right-0 pr-3 flex items-center"
            >
              @if (showPassword()) {
                <svg class="h-5 w-5 text-gray-400 hover:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                        d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"/>
                </svg>
              } @else {
                <svg class="h-5 w-5 text-gray-400 hover:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                        d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                        d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
                </svg>
              }
            </button>
          </div>
          @if (hasError('password', 'required')) {
            <p class="mt-1 text-sm text-red-600 dark:text-red-400">La contraseña es requerida</p>
          }
          @if (hasError('password', 'minlength')) {
            <p class="mt-1 text-sm text-red-600 dark:text-red-400">La contraseña debe tener al menos 8 caracteres</p>
          }
        </div>

        <!-- Recordarme y Olvidaste contraseña -->
        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <input
              id="rememberMe"
              type="checkbox"
              formControlName="rememberMe"
              class="h-4 w-4 text-cermont-primary-600 focus:ring-cermont-primary-500 border-gray-300 rounded"
            />
            <label for="rememberMe" class="ml-2 block text-sm text-gray-700 dark:text-gray-300">
              Recordarme
            </label>
          </div>

          <a 
            routerLink="/auth/forgot-password"
            class="text-sm font-medium text-cermont-primary-600 hover:text-cermont-primary-500 dark:text-cermont-primary-400"
          >
            ¿Olvidaste tu contraseña?
          </a>
        </div>

        <!-- Botón de login -->
        <button
          type="submit"
          [disabled]="loading() || form.invalid"
          class="w-full btn-primary flex items-center justify-center"
        >
          @if (loading()) {
            <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Iniciando sesión...
          } @else {
            Iniciar Sesión
          }
        </button>
      </form>

      <!-- Divider -->
      <div class="mt-6">
        <div class="relative">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-gray-300 dark:border-gray-600"></div>
          </div>
          <div class="relative flex justify-center text-sm">
            <span class="px-2 bg-white dark:bg-gray-800 text-gray-500">¿No tienes cuenta?</span>
          </div>
        </div>

        <div class="mt-6">
          <a
            routerLink="/auth/register"
            class="w-full flex justify-center py-2 px-4 border-2 border-cermont-primary-500 rounded-lg text-sm font-medium text-cermont-primary-600 dark:text-cermont-primary-400 hover:bg-cermont-primary-50 dark:hover:bg-cermont-primary-900/20 transition-colors"
          >
            Crear cuenta nueva
          </a>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <p class="mt-8 text-center text-sm text-gray-600 dark:text-gray-400">
      © 2025 Cermont. Todos los derechos reservados.
    </p>
  </div>
</div>
