// frontend/src/app/features/landing/components/hero-section/hero-section.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { CompanyDataService } from '../../../../core/services/company-data.service';

@Component({
  selector: 'app-hero-section',
  imports: [CommonModule],
  templateUrl: './hero-section.component.html',
  styleUrls: ['./hero-section.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeroSectionComponent {
  protected readonly companyData = inject(CompanyDataService);
  readonly stats = this.companyData.getStats();
  readonly experience = this.companyData.experience;
}

<section
    class="relative min-h-screen flex items-center justify-center overflow-hidden bg-linear-to-b from-white via-gray-50 to-white dark:from-gray-950 dark:via-gray-900 dark:to-gray-950">
    <!-- Background Decorations -->
    <div class="absolute inset-0 overflow-hidden">
        <!-- Gradient Orbs -->
        <div
            class="absolute -top-40 -right-40 w-96 h-96 bg-cermont-primary-500/20 dark:bg-cermont-primary-500/10 rounded-full blur-3xl">
        </div>
        <div
            class="absolute -bottom-40 -left-40 w-96 h-96 bg-cermont-secondary-500/20 dark:bg-cermont-secondary-500/10 rounded-full blur-3xl">
        </div>

        <!-- Grid Pattern -->
        <div
            class="absolute inset-0 bg-[linear-gradient(rgba(0,191,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(0,191,255,0.03)_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_80%_50%_at_50%_50%,black,transparent)]">
        </div>
    </div>

    <!-- Content -->
    <div class="relative z-10 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-20">
        <div class="text-center">
            <!-- Badge -->
            <div
                class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-cermont-primary-100 dark:bg-cermont-primary-900/30 border border-cermont-primary-200 dark:border-cermont-primary-800 mb-8 animate-fade-in">
                <span class="relative flex h-2 w-2">
                    <span
                        class="animate-ping absolute inline-flex h-full w-full rounded-full bg-cermont-primary-500 opacity-75"></span>
                    <span class="relative inline-flex rounded-full h-2 w-2 bg-cermont-primary-600"></span>
                </span>
                <span class="text-sm font-medium text-cermont-primary-700 dark:text-cermont-primary-400">
                    Más de 16 años construyendo confianza
                </span>
            </div>

            <!-- Main Heading -->
            <h1 class="text-5xl md:text-7xl font-extrabold text-gray-900 dark:text-white mb-6 leading-tight animate-fade-in"
                style="animation-delay: 0.1s;">
                Soluciones de
                <span
                    class="bg-linear-to-r from-cermont-primary-600 via-cermont-primary-500 to-cermont-secondary-500 bg-clip-text text-transparent">
                    Construcción
                </span>
                <br />
                e Ingeniería
            </h1>

            <!-- Description -->
            <p class="text-xl md:text-2xl text-gray-600 dark:text-gray-400 max-w-3xl mx-auto mb-10 animate-fade-in"
                style="animation-delay: 0.2s;">
                Generamos soluciones eficientes con más de 16 años de experiencia en construcción,
                mantenimiento y montajes, respaldados por tecnología de última generación.
            </p>

            <!-- CTAs -->
            <div class="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16 animate-fade-in"
                style="animation-delay: 0.3s;">
                <a routerLink="/auth/register"
                    class="inline-flex items-center px-8 py-4 text-lg font-medium text-white bg-linear-to-r from-cermont-primary-600 to-cermont-primary-700 rounded-xl hover:from-cermont-primary-700 hover:to-cermont-primary-800 shadow-xl shadow-cermont-primary-500/30 hover:shadow-2xl hover:shadow-cermont-primary-500/40 transition-all duration-300">
                    <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M13 10V3L4 14h7v7l9-11h-7z" />
                    </svg>
                    Comenzar Ahora
                </a>
                <button (click)="scrollToSection('contacto')"
                    class="inline-flex items-center px-8 py-4 text-lg font-medium text-gray-700 dark:text-gray-300 border-2 border-gray-300 dark:border-gray-700 rounded-xl hover:border-cermont-primary-500 dark:hover:border-cermont-primary-500 hover:text-cermont-primary-600 dark:hover:text-cermont-primary-400 transition-all duration-300">
                    <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                    </svg>
                    Contactar Ventas
                </button>
            </div>

            <!-- Stats Grid -->
            <div class="grid grid-cols-2 md:grid-cols-4 gap-8 max-w-4xl mx-auto animate-fade-in"
                style="animation-delay: 0.4s;">
                @for (stat of stats; track stat.label) {
                <div class="group">
                    <div
                        class="text-4xl md:text-5xl font-bold bg-linear-to-r from-cermont-primary-600 to-cermont-primary-800 dark:from-cermont-primary-400 dark:to-cermont-primary-600 bg-clip-text text-transparent mb-2 transition-transform duration-300 group-hover:scale-110">
                        {{ stat.value }}
                    </div>
                    <div class="text-sm text-gray-600 dark:text-gray-400 font-medium">
                        {{ stat.label }}
                    </div>
                </div>
                }
            </div>

            <!-- Scroll Indicator -->
            <div class="mt-20 animate-bounce">
                <svg class="w-6 h-6 mx-auto text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M19 14l-7 7m0 0l-7-7m7 7V3" />
                </svg>
            </div>
        </div>
    </div>
</section>

// web/src/components/landing/HeroSection.tsx
import Link from 'next/link';
import Image from 'next/image';

export default function HeroSection() {
    return (
        <section className="relative min-h-screen flex items-center hero-pattern overflow-hidden">
            {/* Background Decoration */}
            <div className="absolute inset-0 overflow-hidden pointer-events-none">
                {/* Gradient Orbs */}
                <div className="absolute -top-40 -right-40 w-96 h-96 bg-blue-500/20 rounded-full blur-3xl animate-breath" />
                <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-green-500/20 rounded-full blur-3xl animate-breath" style={{ animationDelay: '2s' }} />

                {/* Grid Pattern */}
                <div
                    className="absolute inset-0 opacity-[0.02] dark:opacity-[0.05]"
                    style={{
                        backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32' width='32' height='32' fill='none' stroke='rgb(0 0 0 / 0.5)'%3e%3cpath d='M0 .5H31.5V32'/%3e%3c/svg%3e")`,
                    }}
                />
            </div>

            <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-32">
                <div className="grid lg:grid-cols-2 gap-12 items-center">
                    {/* Content */}
                    <div className="text-center lg:text-left">
                        {/* Badge */}
                        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-50 dark:bg-blue-500/10 border border-blue-200 dark:border-blue-500/20 mb-6">
                            <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                            <span className="text-sm font-medium text-blue-700 dark:text-blue-400">
                                Más de 15 años de experiencia
                            </span>
                        </div>

                        {/* Title */}
                        <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 dark:text-white leading-tight mb-6">
                            Soluciones Integrales en{' '}
                            <span className="gradient-text">
                                Refrigeración Industrial
                            </span>
                        </h1>

                        {/* Subtitle */}
                        <p className="text-lg text-gray-600 dark:text-gray-400 mb-8 max-w-xl mx-auto lg:mx-0">
                            Ofrecemos servicios de construcción, electricidad, refrigeración, montajes y suministros con los más altos estándares de calidad y tecnología de última generación.
                        </p>

                        {/* CTAs */}
                        <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                            <Link href="/login" className="btn-primary">
                                Acceder al Sistema
                                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                                </svg>
                            </Link>
                            <a href="#servicios" className="btn-secondary">
                                Conocer Servicios
                            </a>
                        </div>

                        {/* Stats */}
                        <div className="flex flex-wrap gap-8 mt-12 justify-center lg:justify-start">
                            <div className="text-center">
                                <div className="text-3xl font-bold text-gray-900 dark:text-white">2008</div>
                                <div className="text-sm text-gray-500 dark:text-gray-400">Fundada</div>
                            </div>
                            <div className="text-center">
                                <div className="text-3xl font-bold text-gray-900 dark:text-white">15+</div>
                                <div className="text-sm text-gray-500 dark:text-gray-400">Años de Experiencia</div>
                            </div>
                            <div className="text-center">
                                <div className="text-3xl font-bold text-gray-900 dark:text-white">100%</div>
                                <div className="text-sm text-gray-500 dark:text-gray-400">Cobertura Nacional</div>
                            </div>
                        </div>
                    </div>

                    {/* Hero Image/Illustration */}
                    <div className="relative hidden lg:block">
                        <div className="relative w-full aspect-square max-w-lg mx-auto">
                            {/* Glow Effect */}
                            <div className="absolute inset-0 gradient-bg rounded-3xl blur-3xl opacity-20 animate-breath" />

                            {/* Main Card */}
                            <div className="relative glass rounded-3xl p-8 border border-gray-200/50 dark:border-gray-700/50 shadow-2xl">
                                {/* Logo */}
                                <div className="w-24 h-24 mx-auto mb-6">
                                    <Image
                                        src="/logo.svg"
                                        alt="Cermont Logo"
                                        width={96}
                                        height={96}
                                        className="w-full h-full object-contain"
                                    />
                                </div>

                                {/* Company Name */}
                                <h2 className="text-2xl font-bold text-center text-gray-900 dark:text-white mb-2">
                                    CERMONT S.A.S
                                </h2>
                                <p className="text-sm text-center text-gray-500 dark:text-gray-400 mb-6">
                                    Sistema de Gestión de Órdenes de Trabajo
                                </p>

                                {/* Features List */}
                                <div className="space-y-3">
                                    {[
                                        'Gestión de Ordenes de Trabajo',
                                        'Control de Planes de Trabajo',
                                        'Registro de Evidencias',
                                        'Reportes en Tiempo Real',
                                    ].map((feature, index) => (
                                        <div
                                            key={index}
                                            className="flex items-center gap-3 p-3 rounded-xl bg-gray-50 dark:bg-gray-800/50"
                                        >
                                            <div className="w-8 h-8 rounded-lg gradient-bg flex items-center justify-center">
                                                <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                                                </svg>
                                            </div>
                                            <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
                                                {feature}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
}
