// apps/web/src/features/ordenes/components/OrdersList.tsx
'use client';

import { useOrders } from '../hooks/use-orders';
import type { OrderStatus, OrderPriority } from '@/types/order';

interface OrdersListProps {
  filters?: {
    estado?: OrderStatus;
    prioridad?: OrderPriority;
    search?: string;
  };
  onOrderClick?: (orderId: string) => void;
}

const estadoColors: Record<OrderStatus, string> = {
  planeacion: 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200',
  ejecucion: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
  completada: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
  cancelada: 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200',
  pausada: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200',
};

const prioridadColors: Record<OrderPriority, string> = {
  baja: 'border-l-gray-400',
  media: 'border-l-blue-400',
  alta: 'border-l-orange-400',
  urgente: 'border-l-red-500',
};

export function OrdersList({ filters, onOrderClick }: OrdersListProps) {
  const { data, isLoading, error, refetch } = useOrders(filters);

  if (isLoading) {
    return (
      <div className="animate-pulse space-y-3">
        {[...Array(5)].map((_, i) => (
          <div key={i} className="h-16 bg-gray-200 dark:bg-gray-700 rounded"></div>
        ))}
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 border border-red-300 bg-red-50 dark:bg-red-900/20 rounded-lg">
        <p className="text-red-600 dark:text-red-400">Error: {error.message}</p>
        <button
          onClick={() => refetch()}
          className="mt-2 text-sm text-red-700 hover:text-red-900 underline"
        >
          Reintentar
        </button>
      </div>
    );
  }

  const orders = data?.data || [];

  if (orders.length === 0) {
    return (
      <div className="p-8 text-center text-gray-500 dark:text-gray-400">
        <svg
          className="w-12 h-12 mx-auto mb-4 text-gray-400"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
          />
        </svg>
        <p>No hay órdenes registradas</p>
        {filters && Object.keys(filters).length > 0 && (
          <p className="text-sm mt-1">Intenta ajustar los filtros</p>
        )}
      </div>
    );
  }

  return (
    <div className="overflow-hidden rounded-lg border border-gray-200 dark:border-gray-700">
      <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
        <thead className="bg-gray-50 dark:bg-gray-800">
          <tr>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
              Número
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
              Cliente
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
              Tipo
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
              Estado
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
              Prioridad
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
              Fecha
            </th>
          </tr>
        </thead>
        <tbody className="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
          {orders.map((order) => (
            <tr
              key={order.id}
              onClick={() => onOrderClick?.(order.id)}
              className={`border-l-4 ${prioridadColors[order.prioridad]} hover:bg-gray-50 dark:hover:bg-gray-800 cursor-pointer transition-colors`}
            >
              <td className="px-6 py-4 whitespace-nowrap">
                <span className="text-sm font-medium text-gray-900 dark:text-white">
                  {order.numero}
                </span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <span className="text-sm text-gray-700 dark:text-gray-300">
                  {order.cliente}
                </span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <span className="text-sm text-gray-600 dark:text-gray-400 capitalize">
                  {order.tipo?.replace('_', ' ') || '-'}
                </span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <span
                  className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${estadoColors[order.estado]}`}
                >
                  {order.estado.replace('_', ' ')}
                </span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap">
                <span className="text-sm text-gray-600 dark:text-gray-400 capitalize">
                  {order.prioridad}
                </span>
              </td>
              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                {new Date(order.createdAt).toLocaleDateString('es-CO')}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// frontend/src/app/features/orders/components/orders-list/orders-list.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { Subject, takeUntil } from 'rxjs';
import { ListOrdenesQuery, Orden, OrdenEstado, Prioridad } from '../../../../core/models';
import { logError } from '../../../../core/utils/logger';
import { OrdersService, PaginatedOrdenes } from '../../services/orders.service';

@Component({
  selector: 'app-orders-list',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  templateUrl: './orders-list.component.html',
  styleUrls: ['./orders-list.component.css'],
})
export class OrdersListComponent implements OnInit, OnDestroy {
  private readonly ordersService = inject(OrdersService);
  private readonly destroy$ = new Subject<void>();

  // Signals para el estado
  ordenes = signal<Orden[]>([]);
  loading = signal(false);
  error = signal<string | null>(null);

  // Filtros y b�squeda
  searchTerm = signal('');
  estadoFilter = signal<string>('');
  prioridadFilter = signal<string>('');

  // Paginaci�n
  currentPage = signal(1);
  pageSize = signal(10);
  totalItems = signal(0);
  totalPages = signal(0);

  // Enums para template
  readonly OrdenEstado = OrdenEstado;
  readonly Prioridad = Prioridad;
  readonly estadosOptions = Object.values(OrdenEstado);
  readonly prioridadesOptions = Object.values(Prioridad);

  ngOnInit() {
    this.loadOrdenes();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  loadOrdenes() {
    this.loading.set(true);
    this.error.set(null);

    const query: ListOrdenesQuery = {
      page: this.currentPage(),
      limit: this.pageSize(),
      search: this.searchTerm() || undefined,
      estado: (this.estadoFilter() as OrdenEstado) || undefined,
      prioridad: (this.prioridadFilter() as Prioridad) || undefined,
    };

    this.ordersService
      .list(query)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (response: PaginatedOrdenes) => {
          // Handle both data and items properties
          this.ordenes.set(response.data ?? []);
          this.totalItems.set(response.total);
          this.totalPages.set(Math.ceil(response.total / this.pageSize()));
          this.loading.set(false);
        },
        error: err => {
          this.error.set('Error al cargar las �rdenes');
          this.loading.set(false);
          logError('Error loading orders', err);
        },
      });
  }

  onSearchChange() {
    this.currentPage.set(1);
    this.loadOrdenes();
  }

  onFilterChange() {
    this.currentPage.set(1);
    this.loadOrdenes();
  }

  goToPage(page: number) {
    if (page >= 1 && page <= this.totalPages()) {
      this.currentPage.set(page);
      this.loadOrdenes();
    }
  }

  getEstadoBadgeClass(estado: string): string {
    const colorMap: Record<string, string> = {
      pendiente: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200',
      planeacion: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
      ejecucion: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200',
      completada: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
      cancelada: 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200',
      pausada: 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200',
    };
    return colorMap[estado] || 'bg-gray-100 text-gray-800';
  }

  getPrioridadBadgeClass(prioridad: string): string {
    const colorMap: Record<string, string> = {
      baja: 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300',
      media: 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300',
      alta: 'bg-orange-100 text-orange-700 dark:bg-orange-900 dark:text-orange-300',
      urgente: 'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300',
    };
    return colorMap[prioridad] || 'bg-gray-100 text-gray-700';
  }

  formatDate(date: string | null | undefined): string {
    if (!date) return '-';
    const d = new Date(date);
    return d.toLocaleDateString('es-CO', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  }

  formatCurrency(amount: number | null | undefined): string {
    if (amount === null || amount === undefined) return '-';
    return new Intl.NumberFormat('es-CO', {
      style: 'currency',
      currency: 'COP',
      minimumFractionDigits: 0,
    }).format(amount);
  }

  clearFilters(): void {
    this.searchTerm.set('');
    this.estadoFilter.set('');
    this.prioridadFilter.set('');
    this.currentPage.set(1);
    this.loadOrdenes();
  }
}

<div class="container mx-auto px-4 py-6">
  <!-- Header -->
  <div class="flex justify-between items-center mb-6">
    <div>
      <h1 class="text-3xl font-bold text-gray-900 dark:text-white">Órdenes de Trabajo</h1>
      <p class="text-gray-600 dark:text-gray-400 mt-1">Gestión y seguimiento de órdenes</p>
    </div>
    <a
      routerLink="nueva"
      class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors"
    >
      Nueva Orden
    </a>
  </div>

  <!-- Filtros y búsqueda -->
  <div
    class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-4 mb-6"
  >
    <div class="flex flex-col md:flex-row gap-4">
      <div class="flex-1">
        <label for="search-ordenes" class="sr-only">Buscar órdenes</label>
        <input
          type="text"
          id="search-ordenes"
          placeholder="Buscar órdenes..."
          class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
          [(ngModel)]="searchTerm"
          (input)="onSearchChange()"
        />
      </div>
      <div class="flex gap-2">
        <select
          class="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
          [(ngModel)]="estadoFilter"
          (change)="onFilterChange()"
        >
          <option value="">Todos los estados</option>
          <option value="pendiente">Pendiente</option>
          <option value="planeacion">Planeación</option>
          <option value="ejecucion">Ejecución</option>
          <option value="pausada">Pausada</option>
          <option value="completada">Completada</option>
          <option value="cancelada">Cancelada</option>
        </select>
        <select
          class="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white"
          [(ngModel)]="prioridadFilter"
          (change)="onFilterChange()"
        >
          <option value="">Todas las prioridades</option>
          <option value="baja">Baja</option>
          <option value="media">Media</option>
          <option value="alta">Alta</option>
          <option value="urgente">Urgente</option>
        </select>
      </div>
    </div>
  </div>

  @if (loading()) {
    <div class="flex justify-center items-center py-12">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
      <span class="ml-3 text-gray-600 dark:text-gray-400">Cargando órdenes...</span>
    </div>
  }

  @if (error()) {
    <div
      class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4 mb-6"
    >
      <div class="flex items-center">
        <svg
          class="w-6 h-6 text-red-600 dark:text-red-400 mr-3"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
          />
        </svg>
        <p class="text-red-800 dark:text-red-200">{{ error() }}</p>
      </div>
    </div>
  }

  @if (ordenes().length > 0) {
    <!-- Tabla de órdenes -->
    <div
      class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden"
    >
      <div class="overflow-x-auto">
        <table class="w-full">
          <thead class="bg-gray-50 dark:bg-gray-700">
            <tr>
              <th
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider"
              >
                Orden
              </th>
              <th
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider"
              >
                Cliente
              </th>
              <th
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider"
              >
                Estado
              </th>
              <th
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider"
              >
                Prioridad
              </th>
              <th
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider"
              >
                Fecha Estimada
              </th>
              <th
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider"
              >
                Presupuesto
              </th>
              <th
                class="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider"
              >
                Acciones
              </th>
            </tr>
          </thead>
          <tbody class="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
            @for (orden of ordenes(); track orden.id) {
              <tr class="hover:bg-gray-50 dark:hover:bg-gray-700">
                <td class="px-6 py-4 whitespace-nowrap">
                  <div>
                    <div class="text-sm font-medium text-gray-900 dark:text-white">
                      {{ orden.numeroOrden }}
                    </div>
                    <div class="text-sm text-gray-500 dark:text-gray-400">
                      {{ orden.descripcion | slice: 0 : 50 }}...
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-white">
                  {{ orden.cliente }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <span
                    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
                    [class]="getEstadoBadgeClass(orden.estado)"
                  >
                    {{ orden.estado }}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <span
                    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium"
                    [class]="getPrioridadBadgeClass(orden.prioridad)"
                  >
                    {{ orden.prioridad }}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-white">
                  {{ formatDate(orden.fechaFinEstimada) }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 dark:text-white">
                  {{ formatCurrency(orden.presupuestoEstimado) }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                  <div class="flex space-x-2">
                    <a
                      [routerLink]="[orden.id]"
                      class="text-blue-600 hover:text-blue-900 dark:text-blue-400 dark:hover:text-blue-300"
                    >
                      Ver
                    </a>
                    <a
                      [routerLink]="[orden.id, 'editar']"
                      class="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300"
                    >
                      Editar
                    </a>
                  </div>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>

    <!-- Paginación -->
    @if (totalPages() > 1) {
      <div class="flex justify-between items-center mt-6">
        <div class="text-sm text-gray-700 dark:text-gray-300">
          Mostrando página {{ currentPage() }} de {{ totalPages() }} ({{ totalItems() }} total)
        </div>
        <div class="flex space-x-2">
          <button
            (click)="goToPage(currentPage() - 1)"
            [disabled]="currentPage() === 1"
            aria-label="Ir a la página anterior"
            class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded-md text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50 dark:hover:bg-gray-700"
          >
            Anterior
          </button>
          <span class="px-3 py-1 text-sm text-gray-700 dark:text-gray-300" aria-live="polite">
            Página {{ currentPage() }} de {{ totalPages() }}
          </span>
          <button
            (click)="goToPage(currentPage() + 1)"
            [disabled]="currentPage() === totalPages()"
            aria-label="Ir a la página siguiente"
            class="px-3 py-1 border border-gray-300 dark:border-gray-600 rounded-md text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-50 dark:hover:bg-gray-700"
          >
            Siguiente
          </button>
        </div>
      </div>
    }
  }

  @if (!loading() && ordenes().length === 0) {
    <div class="text-center py-12">
      <svg
        class="mx-auto h-12 w-12 text-gray-400"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
        />
      </svg>
      <h3 class="mt-2 text-sm font-medium text-gray-900 dark:text-white">No hay órdenes</h3>
      <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
        Comienza creando tu primera orden de trabajo.
      </p>
      <div class="mt-6">
        <a
          routerLink="nueva"
          class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors"
        >
          Crear Orden
        </a>
      </div>
    </div>
  }
</div>
