// apps/frontend/src/components/shared/LoadingSpinner.tsx
import { cn } from '@/lib/utils';

interface LoadingSpinnerProps {
  size?: 'sm' | 'md' | 'lg';
  className?: string;
  text?: string;
  fullScreen?: boolean;
}

const sizeClasses = {
  sm: 'h-6 w-6 border-2',
  md: 'h-10 w-10 border-3',
  lg: 'h-16 w-16 border-4',
};

export default function LoadingSpinner({
  size = 'md',
  className,
  text = 'Cargando...',
  fullScreen = false,
}: LoadingSpinnerProps) {
  const spinner = (
    <div className="flex flex-col items-center gap-4">
      <div
        className={cn(
          'animate-spin rounded-full border-gray-300 border-t-primary',
          sizeClasses[size],
          className
        )}
      />
      {text && <p className="text-sm text-muted-foreground">{text}</p>}
    </div>
  );

  if (fullScreen) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        {spinner}
      </div>
    );
  }

  return spinner;
}

// frontend/src/app/shared/ui/loading-spinner/loading-spinner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-loading-spinner',
  standalone: true,
  imports: [],
  template: `
    <div class="flex items-center justify-center" [class]="containerClass">
      <div class="relative">
        <div
          class="w-12 h-12 border-4 border-gray-200 border-t-brand-500 rounded-full animate-spin"
          [class]="spinnerClass"
        ></div>
        @if (message) {
          <p class="mt-4 text-sm text-gray-600 dark:text-gray-400 text-center">{{ message }}</p>
        }
      </div>
    </div>
  `,
  styles: [
    `
      @keyframes spin {
        to {
          transform: rotate(360deg);
        }
      }
      .animate-spin {
        animation: spin 1s linear infinite;
      }
    `,
  ],
})
export class LoadingSpinnerComponent {
  @Input() message?: string;
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() fullScreen = false;

  get containerClass(): string {
    if (this.fullScreen) {
      return 'fixed inset-0 bg-white/80 dark:bg-gray-900/80 z-50';
    }
    return 'p-8';
  }

  get spinnerClass(): string {
    const sizes = {
      sm: 'w-6 h-6 border-2',
      md: 'w-12 h-12 border-4',
      lg: 'w-16 h-16 border-4',
    };
    return sizes[this.size];
  }
}
