// web/src/layout/AppSidebar.tsx
"use client";
import React, { useEffect, useRef, useState, useCallback } from "react";
import Link from "next/link";
import Image from "next/image";
import { usePathname } from "next/navigation";
import { useSidebar } from "../context/SidebarContext";
import {
    LayoutDashboard,
    ClipboardList,
    Package,
    UserCircle,
    Users,
    PieChart,
    Settings,
    MoreHorizontal,
    ChevronDown
} from "lucide-react";

type NavItem = {
    name: string;
    icon: React.ReactNode;
    path?: string;
    subItems?: { name: string; path: string; pro?: boolean; new?: boolean }[];
};

const navItems: NavItem[] = [
    {
        icon: <LayoutDashboard size={20} />,
        name: "Dashboard",
        path: "/dashboard",
    },
    {
        icon: <ClipboardList size={20} />,
        name: "Órdenes",
        path: "/dashboard/ordenes",
    },
    {
        icon: <Package size={20} />,
        name: "Kits",
        path: "/dashboard/kits",
    },
    {
        icon: <UserCircle size={20} />,
        name: "Clientes",
        path: "/dashboard/clientes",
    },
    {
        icon: <Users size={20} />,
        name: "Técnicos",
        path: "/dashboard/tecnicos",
    },
    {
        name: "Reportes",
        icon: <PieChart size={20} />,
        subItems: [
            { name: "Financieros", path: "/dashboard/reportes/financieros" },
            { name: "Operativos", path: "/dashboard/reportes/operativos" },
        ],
    },
    {
        name: "Configuración",
        icon: <Settings size={20} />,
        path: "/dashboard/config",
    },
];

const AppSidebar: React.FC = () => {
    const { isExpanded, isMobileOpen, isHovered, setIsHovered } = useSidebar();
    const pathname = usePathname();

    const renderMenuItems = (navItems: NavItem[]) => (
        <ul className="flex flex-col gap-4">
            {navItems.map((nav, index) => (
                <li key={nav.name}>
                    {nav.subItems ? (
                        <button
                            onClick={() => handleSubmenuToggle(index)}
                            className={`menu-item group ${openSubmenu?.index === index
                                    ? "menu-item-active"
                                    : "menu-item-inactive"
                                } cursor-pointer ${!isExpanded && !isHovered ? "lg:justify-center" : "lg:justify-start"
                                }`}
                        >
                            <span
                                className={`${openSubmenu?.index === index
                                        ? "menu-item-icon-active"
                                        : "menu-item-icon-inactive"
                                    }`}
                            >
                                {nav.icon}
                            </span>
                            {(isExpanded || isHovered || isMobileOpen) && (
                                <span className={`menu-item-text`}>{nav.name}</span>
                            )}
                            {(isExpanded || isHovered || isMobileOpen) && (
                                <ChevronDown
                                    className={`ml-auto w-5 h-5 transition-transform duration-200 ${openSubmenu?.index === index ? "rotate-180 text-brand-500" : ""
                                        }`}
                                />
                            )}
                        </button>
                    ) : (
                        nav.path && (
                            <Link
                                href={nav.path}
                                className={`menu-item group ${isActive(nav.path) ? "menu-item-active" : "menu-item-inactive"
                                    }`}
                            >
                                <span
                                    className={`${isActive(nav.path)
                                            ? "menu-item-icon-active"
                                            : "menu-item-icon-inactive"
                                        }`}
                                >
                                    {nav.icon}
                                </span>
                                {(isExpanded || isHovered || isMobileOpen) && (
                                    <span className={`menu-item-text`}>{nav.name}</span>
                                )}
                            </Link>
                        )
                    )}
                    {nav.subItems && (isExpanded || isHovered || isMobileOpen) && (
                        <div
                            ref={(el) => {
                                subMenuRefs.current[`main-${index}`] = el;
                            }}
                            className="overflow-hidden transition-all duration-300"
                            style={{
                                height:
                                    openSubmenu?.index === index
                                        ? `${subMenuHeight[`main-${index}`]}px`
                                        : "0px",
                            }}
                        >
                            <ul className="mt-2 space-y-1 ml-9">
                                {nav.subItems.map((subItem) => (
                                    <li key={subItem.name}>
                                        <Link
                                            href={subItem.path}
                                            className={`menu-dropdown-item ${isActive(subItem.path)
                                                    ? "menu-dropdown-item-active"
                                                    : "menu-dropdown-item-inactive"
                                                }`}
                                        >
                                            {subItem.name}
                                        </Link>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    )}
                </li>
            ))}
        </ul>
    );

    const [openSubmenu, setOpenSubmenu] = useState<{
        index: number;
    } | null>(null);
    const [subMenuHeight, setSubMenuHeight] = useState<Record<string, number>>({});
    const subMenuRefs = useRef<Record<string, HTMLDivElement | null>>({});

    const isActive = useCallback((path: string) => path === pathname, [pathname]);

    useEffect(() => {
        let submenuMatched = false;
        navItems.forEach((nav, index) => {
            if (nav.subItems) {
                nav.subItems.forEach((subItem) => {
                    if (isActive(subItem.path)) {
                        setOpenSubmenu({ index });
                        submenuMatched = true;
                    }
                });
            }
        });

        if (!submenuMatched) {
            setOpenSubmenu(null);
        }
    }, [pathname, isActive]);

    useEffect(() => {
        if (openSubmenu !== null) {
            const key = `main-${openSubmenu.index}`;
            if (subMenuRefs.current[key]) {
                setSubMenuHeight((prevHeights) => ({
                    ...prevHeights,
                    [key]: subMenuRefs.current[key]?.scrollHeight || 0,
                }));
            }
        }
    }, [openSubmenu]);

    const handleSubmenuToggle = (index: number) => {
        setOpenSubmenu((prevOpenSubmenu) => {
            if (prevOpenSubmenu && prevOpenSubmenu.index === index) {
                return null;
            }
            return { index };
        });
    };

    return (
        <aside
            className={`fixed mt-16 flex flex-col lg:mt-0 top-0 px-5 left-0 bg-white dark:bg-gray-900 dark:border-gray-800 text-gray-900 h-screen transition-all duration-300 ease-in-out z-50 border-r border-gray-200 
        ${isExpanded || isMobileOpen
                    ? "w-[290px]"
                    : isHovered
                        ? "w-[290px]"
                        : "w-[90px]"
                }
        ${isMobileOpen ? "translate-x-0" : "-translate-x-full"}
        lg:translate-x-0`}
            onMouseEnter={() => !isExpanded && setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
        >
            <div
                className={`py-8 flex  ${!isExpanded && !isHovered ? "lg:justify-center" : "justify-start"
                    }`}
            >
                <Link href="/dashboard">
                    {isExpanded || isHovered || isMobileOpen ? (
                        <div className="flex items-center gap-2">
                            <Image
                                src="/logo.svg"
                                alt="Cermont"
                                width={150}
                                height={40}
                                className="object-contain"
                            />
                        </div>
                    ) : (
                        <Image
                            src="/logo.svg"
                            alt="Cermont"
                            width={40}
                            height={40}
                            className="object-contain"
                        />
                    )}
                </Link>
            </div>
            <div className="flex flex-col overflow-y-auto duration-300 ease-linear no-scrollbar">
                <nav className="mb-6">
                    <div className="flex flex-col gap-4">
                        <div>
                            <h2
                                className={`mb-4 text-xs uppercase flex leading-[20px] text-gray-400 ${!isExpanded && !isHovered
                                        ? "lg:justify-center"
                                        : "justify-start"
                                    }`}
                            >
                                {isExpanded || isHovered || isMobileOpen ? (
                                    "Menu"
                                ) : (
                                    <MoreHorizontal size={20} />
                                )}
                            </h2>
                            {renderMenuItems(navItems)}
                        </div>
                    </div>
                </nav>
            </div>
        </aside>
    );
};

export default AppSidebar;

// apps/web/src/app/shared/layout/app-sidebar/app-sidebar.component.ts
import { CommonModule } from '@angular/common';
import { Component, ElementRef, OnDestroy, OnInit, QueryList, ViewChildren, ChangeDetectorRef, inject } from '@angular/core';
import { SidebarService } from '../../services/sidebar.service';
import { NavigationEnd, Router, RouterModule } from '@angular/router';
import { SafeHtmlPipe } from '../../pipe/safe-html.pipe';
import { SidebarWidgetComponent } from './app-sidebar-widget.component';
import { combineLatest, firstValueFrom, Observable, Subscription } from 'rxjs';

type NavItem = {
  name: string;
  icon: string;
  path?: string;
  new?: boolean;
  subItems?: { name: string; path: string; pro?: boolean; new?: boolean }[];
};

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    SafeHtmlPipe,
    SidebarWidgetComponent
  ],
  templateUrl: './app-sidebar.component.html',
})
export class AppSidebarComponent implements OnInit, OnDestroy {
  public readonly sidebarService = inject(SidebarService);
  private readonly router = inject(Router);
  private readonly cdr = inject(ChangeDetectorRef);

  // Main nav items - Navegación CERMONT (producción)
  navItems: NavItem[] = [
    {
      icon: `<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M5.5 3.25C4.25736 3.25 3.25 4.25736 3.25 5.5V8.99998C3.25 10.2426 4.25736 11.25 5.5 11.25H9C10.2426 11.25 11.25 10.2426 11.25 8.99998V5.5C11.25 4.25736 10.2426 3.25 9 3.25H5.5ZM4.75 5.5C4.75 5.08579 5.08579 4.75 5.5 4.75H9C9.41421 4.75 9.75 5.08579 9.75 5.5V8.99998C9.75 9.41419 9.41421 9.74998 9 9.74998H5.5C5.08579 9.74998 4.75 9.41419 4.75 8.99998V5.5ZM5.5 12.75C4.25736 12.75 3.25 13.7574 3.25 15V18.5C3.25 19.7426 4.25736 20.75 5.5 20.75H9C10.2426 20.75 11.25 19.7427 11.25 18.5V15C11.25 13.7574 10.2426 12.75 9 12.75H5.5ZM4.75 15C4.75 14.5858 5.08579 14.25 5.5 14.25H9C9.41421 14.25 9.75 14.5858 9.75 15V18.5C9.75 18.9142 9.41421 19.25 9 19.25H5.5C5.08579 19.25 4.75 18.9142 4.75 18.5V15ZM12.75 5.5C12.75 4.25736 13.7574 3.25 15 3.25H18.5C19.7426 3.25 20.75 4.25736 20.75 5.5V8.99998C20.75 10.2426 19.7426 11.25 18.5 11.25H15C13.7574 11.25 12.75 10.2426 12.75 8.99998V5.5ZM15 4.75C14.5858 4.75 14.25 5.08579 14.25 5.5V8.99998C14.25 9.41419 14.5858 9.74998 15 9.74998H18.5C18.9142 9.74998 19.25 9.41419 19.25 8.99998V5.5C19.25 5.08579 18.9142 4.75 18.5 4.75H15ZM15 12.75C13.7574 12.75 12.75 13.7574 12.75 15V18.5C12.75 19.7426 13.7574 20.75 15 20.75H18.5C19.7426 20.75 20.75 19.7427 20.75 18.5V15C20.75 13.7574 19.7426 12.75 18.5 12.75H15ZM14.25 15C14.25 14.5858 14.5858 14.25 15 14.25H18.5C18.9142 14.25 19.25 14.5858 19.25 15V18.5C19.25 18.9142 18.9142 19.25 18.5 19.25H15C14.5858 19.25 14.25 18.9142 14.25 18.5V15Z" fill="currentColor"></path></svg>`,
      name: "Dashboard",
      path: "/dashboard",
    },
    {
      icon: `<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.25 5.5C3.25 4.25736 4.25736 3.25 5.5 3.25H18.5C19.7426 3.25 20.75 4.25736 20.75 5.5V18.5C20.75 19.7426 19.7426 20.75 18.5 20.75H5.5C4.25736 20.75 3.25 19.7426 3.25 18.5V5.5ZM5.5 4.75C5.08579 4.75 4.75 5.08579 4.75 5.5V8.58325L19.25 8.58325V5.5C19.25 5.08579 18.9142 4.75 18.5 4.75H5.5ZM19.25 10.0833H15.416V13.9165H19.25V10.0833ZM13.916 10.0833L10.083 10.0833V13.9165L13.916 13.9165V10.0833ZM8.58301 10.0833H4.75V13.9165H8.58301V10.0833ZM4.75 18.5V15.4165H8.58301V19.25H5.5C5.08579 19.25 4.75 18.9142 4.75 18.5ZM10.083 19.25V15.4165L13.916 15.4165V19.25H10.083ZM15.416 19.25V15.4165H19.25V18.5C19.25 18.9142 18.9142 19.25 18.5 19.25H15.416Z" fill="currentColor"></path></svg>`,
      name: "Órdenes",
      path: "/dashboard/ordenes",
    },
    {
      icon: `<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M5.5 3.25C4.25736 3.25 3.25 4.25736 3.25 5.5V18.5C3.25 19.7426 4.25736 20.75 5.5 20.75H18.5001C19.7427 20.75 20.7501 19.7426 20.7501 18.5V5.5C20.7501 4.25736 19.7427 3.25 18.5001 3.25H5.5ZM4.75 5.5C4.75 5.08579 5.08579 4.75 5.5 4.75H18.5001C18.9143 4.75 19.2501 5.08579 19.2501 5.5V18.5C19.2501 18.9142 18.9143 19.25 18.5001 19.25H5.5C5.08579 19.25 4.75 18.9142 4.75 18.5V5.5ZM6.25005 9.7143C6.25005 9.30008 6.58583 8.9643 7.00005 8.9643L17 8.96429C17.4143 8.96429 17.75 9.30008 17.75 9.71429C17.75 10.1285 17.4143 10.4643 17 10.4643L7.00005 10.4643C6.58583 10.4643 6.25005 10.1285 6.25005 9.7143ZM6.25005 14.2857C6.25005 13.8715 6.58583 13.5357 7.00005 13.5357H17C17.4143 13.5357 17.75 13.8715 17.75 14.2857C17.75 14.6999 17.4143 15.0357 17 15.0357H7.00005C6.58583 15.0357 6.25005 14.6999 6.25005 14.2857Z" fill="currentColor"></path></svg>`,
      name: "HES",
      path: "/dashboard/hes",
    },
    {
      icon: `<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M8 2C8.41421 2 8.75 2.33579 8.75 2.75V3.75H15.25V2.75C15.25 2.33579 15.5858 2 16 2C16.4142 2 16.75 2.33579 16.75 2.75V3.75H18.5C19.7426 3.75 20.75 4.75736 20.75 6V9V19C20.75 20.2426 19.7426 21.25 18.5 21.25H5.5C4.25736 21.25 3.25 20.2426 3.25 19V9V6C3.25 4.75736 4.25736 3.75 5.5 3.75H7.25V2.75C7.25 2.33579 7.58579 2 8 2ZM8 5.25H5.5C5.08579 5.25 4.75 5.58579 4.75 6V8.25H19.25V6C19.25 5.58579 18.9142 5.25 18.5 5.25H16H8ZM19.25 9.75H4.75V19C4.75 19.4142 5.08579 19.75 5.5 19.75H18.5C18.9142 19.75 19.25 19.4142 19.25 19V9.75Z" fill="currentColor"></path></svg>`,
      name: "Calendario",
      path: "/dashboard/calendario",
    },
    {
      icon: `<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 3.5C7.30558 3.5 3.5 7.30558 3.5 12C3.5 14.1526 4.3002 16.1184 5.61936 17.616C6.17279 15.3096 8.24852 13.5955 10.7246 13.5955H13.2746C15.7509 13.5955 17.8268 15.31 18.38 17.6167C19.6996 16.119 20.5 14.153 20.5 12C20.5 7.30558 16.6944 3.5 12 3.5ZM17.0246 18.8566V18.8455C17.0246 16.7744 15.3457 15.0955 13.2746 15.0955H10.7246C8.65354 15.0955 6.97461 16.7744 6.97461 18.8455V18.856C8.38223 19.8895 10.1198 20.5 12 20.5C13.8798 20.5 15.6171 19.8898 17.0246 18.8566ZM2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12ZM11.9991 7.25C10.8847 7.25 9.98126 8.15342 9.98126 9.26784C9.98126 10.3823 10.8847 11.2857 11.9991 11.2857C13.1135 11.2857 14.0169 10.3823 14.0169 9.26784C14.0169 8.15342 13.1135 7.25 11.9991 7.25ZM8.48126 9.26784C8.48126 7.32499 10.0563 5.75 11.9991 5.75C13.9419 5.75 15.5169 7.32499 15.5169 9.26784C15.5169 11.2107 13.9419 12.7857 11.9991 12.7857C10.0563 12.7857 8.48126 11.2107 8.48126 9.26784Z" fill="currentColor"></path></svg>`,
      name: "Mi Perfil",
      path: "/dashboard/perfil",
    },
    {
      name: "Reportes",
      icon: `<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C11.5858 2 11.25 2.33579 11.25 2.75V12C11.25 12.4142 11.5858 12.75 12 12.75H21.25C21.6642 12.75 22 12.4142 22 12C22 6.47715 17.5228 2 12 2ZM12.75 11.25V3.53263C16.8196 3.97378 20.0262 7.18044 20.4674 11.25H12.75ZM2 12C2 7.25083 5.31065 3.27489 9.75 2.25415V3.80099C6.14748 4.78734 3.5 8.0845 3.5 12C3.5 16.6944 7.30558 20.5 12 20.5C15.9155 20.5 19.2127 17.8525 20.199 14.25H21.7459C20.7251 18.6894 16.7492 22 12 22C6.47715 22 2 17.5229 2 12Z" fill="currentColor"></path></svg>`,
      subItems: [
        { name: "Financieros", path: "/dashboard/reportes/financieros" },
        { name: "Operativos", path: "/dashboard/reportes/operativos" },
      ],
    },
    {
      name: "Configuración",
      icon: `<svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.0175 2.74902C11.0175 2.3348 11.3533 1.99902 11.7675 1.99902H12.2325C12.6467 1.99902 12.9825 2.3348 12.9825 2.74902V3.71725C14.1629 3.92619 15.2684 4.36878 16.2505 5.00237L16.9318 4.32104C17.2247 4.02815 17.6996 4.02815 17.9925 4.32104L18.3145 4.64305C18.6074 4.93595 18.6074 5.41082 18.3145 5.70371L17.6336 6.38467C18.2655 7.36584 18.7069 8.46994 18.9155 9.64893H19.8825C20.2967 9.64893 20.6325 9.98471 20.6325 10.3989V10.8639C20.6325 11.2782 20.2967 11.6139 19.8825 11.6139H18.9155C18.7069 12.7929 18.2655 13.897 17.6336 14.8782L18.3145 15.5591C18.6074 15.852 18.6074 16.3269 18.3145 16.6198L17.9925 16.9418C17.6996 17.2347 17.2247 17.2347 16.9318 16.9418L16.2505 16.2605C15.2684 16.8941 14.1629 17.3366 12.9825 17.5456V18.5139C12.9825 18.9281 12.6467 19.2639 12.2325 19.2639H11.7675C11.3533 19.2639 11.0175 18.9281 11.0175 18.5139V17.5456C9.8371 17.3366 8.73164 16.8941 7.74953 16.2605L7.06821 16.9418C6.77531 17.2347 6.30044 17.2347 6.00755 16.9418L5.68554 16.6198C5.39264 16.3269 5.39264 15.852 5.68554 15.5591L6.36639 14.8782C5.73445 13.897 5.29314 12.7929 5.08453 11.6139H4.1175C3.70328 11.6139 3.3675 11.2782 3.3675 10.8639V10.3989C3.3675 9.98471 3.70328 9.64893 4.1175 9.64893H5.08453C5.29314 8.46994 5.73445 7.36584 6.36639 6.38467L5.68554 5.70371C5.39264 5.41082 5.39264 4.93595 5.68554 4.64305L6.00755 4.32104C6.30044 4.02815 6.77531 4.02815 7.06821 4.32104L7.74953 5.00237C8.73164 4.36878 9.8371 3.92619 11.0175 3.71725V2.74902ZM12 15.5C14.4853 15.5 16.5 13.4853 16.5 11C16.5 8.51472 14.4853 6.5 12 6.5C9.51472 6.5 7.5 8.51472 7.5 11C7.5 13.4853 9.51472 15.5 12 15.5Z" fill="currentColor"></path></svg>`,
      path: "/dashboard/configuracion",
    },
  ];

  // Others nav items (vacío - solo producción)
  othersItems: NavItem[] = [];

  openSubmenu: string | null | number = null;
  subMenuHeights: { [key: string]: number } = {};
  @ViewChildren('subMenu') subMenuRefs!: QueryList<ElementRef>;

  readonly isExpanded$: Observable<boolean>;
  readonly isMobileOpen$: Observable<boolean>;
  readonly isHovered$: Observable<boolean>;

  private subscription: Subscription = new Subscription();

  constructor() {
    this.isExpanded$ = this.sidebarService.isExpanded$;
    this.isMobileOpen$ = this.sidebarService.isMobileOpen$;
    this.isHovered$ = this.sidebarService.isHovered$;
  }

  ngOnInit() {
    this.subscription.add(
      this.router.events.subscribe(event => {
        if (event instanceof NavigationEnd) {
          this.setActiveMenuFromRoute(this.router.url);
        }
      })
    );

    this.subscription.add(
      combineLatest([this.isExpanded$, this.isMobileOpen$, this.isHovered$] as const).subscribe(
        ([isExpanded, isMobileOpen, isHovered]) => {
          const isCollapsedReal = !isExpanded && !isMobileOpen && !isHovered;
          if (isCollapsedReal) {
            this.openSubmenu = null;
            this.subMenuHeights = {};
          }
          this.cdr.detectChanges();
        }
      )
    );

    this.setActiveMenuFromRoute(this.router.url);
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }

  isActive(path: string): boolean {
    return this.router.url === path;
  }

  private getNavItem(section: string, index: number): NavItem | undefined {
    const list = section === 'others' ? this.othersItems : this.navItems;
    return list[index];
  }

  async toggleSubmenu(section: string, index: number) {
    const key = `${section}-${index}`;

    const [isExpanded, isMobileOpen, isHovered] = await firstValueFrom(
      combineLatest([this.isExpanded$, this.isMobileOpen$, this.isHovered$] as const)
    );
    const isCollapsedReal = !isExpanded && !isMobileOpen && !isHovered;

    if (isCollapsedReal) {
      const nav = this.getNavItem(section, index);
      const firstSubItem = nav?.subItems?.[0];
      if (firstSubItem?.path) {
        await this.router.navigateByUrl(firstSubItem.path);
      }
      return;
    }

    if (this.openSubmenu === key) {
      this.openSubmenu = null;
      this.subMenuHeights[key] = 0;
    } else {
      this.openSubmenu = key;

      setTimeout(() => {
        const el = document.getElementById(key);
        if (el) {
          this.subMenuHeights[key] = el.scrollHeight;
          this.cdr.detectChanges();
        }
      });
    }
  }

  async onSidebarMouseEnter(): Promise<void> {
    const expanded = await firstValueFrom(this.isExpanded$);
    if (!expanded) {
      this.sidebarService.setHovered(true);
    }
  }

  private setActiveMenuFromRoute(currentUrl: string) {
    const menuGroups = [
      { items: this.navItems, prefix: 'main' },
      { items: this.othersItems, prefix: 'others' },
    ];

    menuGroups.forEach(group => {
      group.items.forEach((nav, i) => {
        if (nav.subItems) {
          nav.subItems.forEach(subItem => {
            if (currentUrl === subItem.path) {
              const key = `${group.prefix}-${i}`;
              this.openSubmenu = key;

              setTimeout(() => {
                const el = document.getElementById(key);
                if (el) {
                  this.subMenuHeights[key] = el.scrollHeight;
                  this.cdr.detectChanges();
                }
              });
            }
          });
        }
      });
    });
  }

  async onSubmenuClick(): Promise<void> {
    const isMobile = await firstValueFrom(this.isMobileOpen$);
    if (isMobile) {
      this.sidebarService.setMobileOpen(false);
    }
  }
}

<aside
  class="fixed flex flex-col top-0 px-5 left-0 bg-white dark:bg-gray-900 dark:border-gray-800 text-gray-900 h-screen transition-all duration-300 ease-in-out z-50 border-r border-gray-200"
  [ngClass]="{
    'w-72.5':
      (isExpanded$ | async) || (isMobileOpen$ | async) || (isHovered$ | async),
    'w-22.5': !(
      (isExpanded$ | async) ||
      (isMobileOpen$ | async) ||
      (isHovered$ | async)
    ),
    'translate-x-0': isMobileOpen$ | async,
    '-translate-x-full': (isMobileOpen$ | async) === false,
    'xl:translate-x-0': true
  }" (mouseenter)="onSidebarMouseEnter()" (mouseleave)="sidebarService.setHovered(false)">
  <div class="py-8 flex" [ngClass]="{
      'xl:justify-center': !((isExpanded$ | async) || (isHovered$ | async)),
      'justify-start': (isExpanded$ | async) || (isHovered$ | async)
    }">
    <a routerLink="/">
      @if ((isExpanded$ | async) || (isHovered$ | async) || (isMobileOpen$ | async)) {
      <img class="dark:hidden" src="/logo.svg" alt="Cermont Logo" width="150" height="40" />
      <img class="hidden dark:block" src="/logo.svg" alt="Cermont Logo" width="150" height="40" />
      } @else {
      <img src="/icon.svg" alt="Cermont" width="32" height="32" />
      }
    </a>
  </div>

  <div class="flex flex-col overflow-y-auto duration-300 ease-linear no-scrollbar">
    <nav class="mb-6">
      <div class="flex flex-col gap-4">
        <!-- Menu Section -->
        <div>
          <h2 class="mb-4 text-xs uppercase flex leading-5 text-gray-400" [ngClass]="{
              'xl:justify-center': !(
                (isExpanded$ | async) || (isHovered$ | async)
              ),
              'justify-start': (isExpanded$ | async) || (isHovered$ | async)
            }">
            @if ((isExpanded$ | async) || (isHovered$ | async) || (isMobileOpen$ | async))
            { Menu }
            @else {
            <svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"
              class="size-6">
              <path fill-rule="evenodd" clip-rule="evenodd"
                d="M5.99915 10.2451C6.96564 10.2451 7.74915 11.0286 7.74915 11.9951V12.0051C7.74915 12.9716 6.96564 13.7551 5.99915 13.7551C5.03265 13.7551 4.24915 12.9716 4.24915 12.0051V11.9951C4.24915 11.0286 5.03265 10.2451 5.99915 10.2451ZM17.9991 10.2451C18.9656 10.2451 19.7491 11.0286 19.7491 11.9951V12.0051C19.7491 12.9716 18.9656 13.7551 17.9991 13.7551C17.0326 13.7551 16.2491 12.9716 16.2491 12.0051V11.9951C16.2491 11.0286 17.0326 10.2451 17.9991 10.2451ZM13.7491 11.9951C13.7491 11.0286 12.9656 10.2451 11.9991 10.2451C11.0326 10.2451 10.2491 11.0286 10.2491 11.9951V12.0051C10.2491 12.9716 11.0326 13.7551 11.9991 13.7551C12.9656 13.7551 13.7491 12.9716 13.7491 12.0051V11.9951Z"
                fill="currentColor"></path>
            </svg>
            }
          </h2>
          <ul class="flex flex-col gap-1">
            @for (nav of navItems; track $index;let i = $index) {
            <li>
              @if (nav.subItems) {
              <button (click)="toggleSubmenu('main',i)" class="menu-item group cursor-pointer"
                [class.menu-item-active]="openSubmenu === 'main-' + i"
                [class.menu-item-inactive]="openSubmenu !== 'main-' + i" [ngClass]="{
                    'xl:justify-center': !(
                      (isExpanded$ | async) || (isHovered$ | async)
                    ),
                    'xl:justify-start':
                      (isExpanded$ | async) || (isHovered$ | async)
                  }">
                <span class="menu-item-icon-size" [class.menu-item-icon-active]="openSubmenu === 'main-' + i"
                  [class.menu-item-icon-inactive]="openSubmenu !== 'main-' + i" [innerHTML]="nav.icon | safeHtml">
                </span>
                @if ((isExpanded$ | async) || (isHovered$ | async) ||
                (isMobileOpen$ | async)) {

                <span class="menu-item-text">
                  {{ nav.name }}
                </span>
                }
                @if (nav.new && ((isExpanded$ | async) || (isHovered$ |
                async) || (isMobileOpen$ | async))) {
                <span class="ml-auto absolute right-10 menu-dropdown-badge" [ngClass]="{
                      'menu-dropdown-badge-active': openSubmenu === 'main-' + i,
                      'menu-dropdown-badge-inactive': openSubmenu !== 'main-' + i
                    }">
                  new
                </span>
                }
                @if ((isExpanded$ | async) || (isHovered$ | async) ||
                (isMobileOpen$ | async)) {
                <svg [ngClass]="{
                      'rotate-180 text-brand-500': openSubmenu === 'main-' + i
                    }" width="1em" height="1em" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"
                  class="ml-auto w-5 h-5 transition-transform duration-200">
                  <path d="M4.79175 7.396L10.0001 12.6043L15.2084 7.396" stroke="currentColor" stroke-width="1.5"
                    stroke-linecap="round" stroke-linejoin="round"></path>
                </svg>
                }
              </button>
              <div class="overflow-hidden transition-all duration-300" [id]="'main-' + i" [style.display]="
                    (isExpanded$ | async) || (isHovered$ | async) || (isMobileOpen$ | async) 
                      ? 'block' 
                      : 'none'
                  " [ngStyle]="{
                    height:
                      openSubmenu === 'main-' + i
                        ? (subMenuHeights['main-' + i] || 0) + 'px'
                        : '0px'
                  }">
                <ul class="mt-2 space-y-1 ml-9">
                  @for (subItem of nav.subItems; track $index) {
                  <li>
                    <a [routerLink]="subItem.path" routerLinkActive="" (click)="onSubmenuClick()"
                      class="menu-dropdown-item" [ngClass]="{
                              'menu-dropdown-item-inactive': !isActive(subItem.path),
                              'menu-dropdown-item-active': isActive(subItem.path),
                            }">
                      {{ subItem.name }}
                      <span class="flex items-center gap-1 ml-auto">
                        @if (subItem.new) {
                        <span class="menu-dropdown-badge" [ngClass]="{
                              'menu-dropdown-badge-active': isActive(
                                subItem.path
                              ),
                              'menu-dropdown-badge-inactive': !isActive(
                                subItem.path
                              )
                            }">
                          new
                        </span>
                        }
                        @if (subItem.pro) {
                        <span class="ml-auto menu-dropdown-badge-pro" [ngClass]="{
                              'menu-dropdown-badge-pro-active': isActive(
                                subItem.path
                              ),
                              'menu-dropdown-badge-pro-inactive': !isActive(
                                subItem.path
                              )
                            }">
                          pro
                        </span>
                        }
                      </span>
                    </a>
                  </li>
                  }
                </ul>
              </div>
              } @else {
              @if (nav.path) {
              <a [routerLink]="nav.path" routerLinkActive="menu-item-active" class="menu-item group"
                [ngClass]="{
                  'menu-item-inactive': !isActive(nav.path),
                  'xl:justify-center': !((isExpanded$ | async) || (isHovered$ | async)),
                  'xl:justify-start': (isExpanded$ | async) || (isHovered$ | async)
                }">
                <span class="menu-item-icon-size" [ngClass]="{
                      'menu-item-icon-active': isActive(nav.path),
                      'menu-item-icon-inactive': !isActive(nav.path)
                    }" [innerHTML]="nav.icon | safeHtml">
                </span>
                <span class="menu-item-text">
                  @if ((isExpanded$ | async) || (isHovered$ | async) || (isMobileOpen$ | async)) {
                  {{ nav.name }}
                  }
                </span>
              </a>
              }
              }
            </li>
            }
          </ul>
        </div>
        <!-- end main menu -->

        <!-- Support Section -->
        <!-- end support section -->

        <!-- Others Section -->
        <div>
          <h2 class="mb-4 text-xs uppercase flex leading-5 text-gray-400" [ngClass]="{
              'xl:justify-center': !(
                (isExpanded$ | async) || (isHovered$ | async)
              ),
              'justify-start': (isExpanded$ | async) || (isHovered$ | async)
            }">
            @if (
            (isExpanded$ | async) ||
            (isHovered$ | async) ||
            (isMobileOpen$ | async)
            ) {
            Others
            } @else {
            <svg width="1em" height="1em" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"
              class="size-6">
              <path fill-rule="evenodd" clip-rule="evenodd"
                d="M5.99915 10.2451C6.96564 10.2451 7.74915 11.0286 7.74915 11.9951V12.0051C7.74915 12.9716 6.96564 13.7551 5.99915 13.7551C5.03265 13.7551 4.24915 12.9716 4.24915 12.0051V11.9951C4.24915 11.0286 5.03265 10.2451 5.99915 10.2451ZM17.9991 10.2451C18.9656 10.2451 19.7491 11.0286 19.7491 11.9951V12.0051C19.7491 12.9716 18.9656 13.7551 17.9991 13.7551C17.0326 13.7551 16.2491 12.9716 16.2491 12.0051V11.9951C16.2491 11.0286 17.0326 10.2451 17.9991 10.2451ZM13.7491 11.9951C13.7491 11.0286 12.9656 10.2451 11.9991 10.2451C11.0326 10.2451 10.2491 11.0286 10.2491 11.9951V12.0051C10.2491 12.9716 11.0326 13.7551 11.9991 13.7551C12.9656 13.7551 13.7491 12.9716 13.7491 12.0051V11.9951Z"
                fill="currentColor"></path>
            </svg>
            }
          </h2>

          <ul class="flex flex-col gap-1">
            @for (nav of othersItems; track $index;let i = $index) {
            <li>
              @if (nav.subItems) {
              <button (click)="toggleSubmenu('others',i)" class="menu-item group cursor-pointer" [ngClass]="{
                     'menu-item-active': openSubmenu === 'others-' + i,
                     'menu-item-inactive': openSubmenu !== 'others-' + i,
                    'xl:justify-center': !(
                      (isExpanded$ | async) || (isHovered$ | async)
                    ),
                    'xl:justify-start':
                      (isExpanded$ | async) || (isHovered$ | async)
                  }">
                <span class="menu-item-icon-size" [ngClass]="{
                      'menu-item-icon-active': openSubmenu === 'others-' + i,
                      'menu-item-icon-inactive': openSubmenu !== 'others-' + i,
                    }" [innerHTML]="nav.icon | safeHtml">
                </span>
                @if ((isExpanded$ | async) || (isHovered$ | async) ||
                (isMobileOpen$ | async)) {

                <span class="menu-item-text">
                  {{ nav.name }}
                </span>
                }
                @if (nav.new && ((isExpanded$ | async) || (isHovered$ |
                async) || (isMobileOpen$ | async))) {
                <span class="ml-auto absolute right-10 menu-dropdown-badge" [ngClass]="{
                      'menu-dropdown-badge-active': openSubmenu === 'others-' + i,
                      'menu-dropdown-badge-inactive': openSubmenu !== 'others-' + i
                    }">
                  new
                </span>
                }
                @if ((isExpanded$ | async) || (isHovered$ | async) ||
                (isMobileOpen$ | async)) {
                <svg [ngClass]="{
                      'rotate-180 text-brand-500': openSubmenu === 'others-' + i
                    }" width="1em" height="1em" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"
                  class="ml-auto w-5 h-5 transition-transform duration-200">
                  <path d="M4.79175 7.396L10.0001 12.6043L15.2084 7.396" stroke="currentColor" stroke-width="1.5"
                    stroke-linecap="round" stroke-linejoin="round"></path>
                </svg>
                }
              </button>
              <div class="overflow-hidden transition-all duration-300" [id]="'others-' + i" [style.display]="
                    (isExpanded$ | async) || (isHovered$ | async) || (isMobileOpen$ | async) 
                      ? 'block' 
                      : 'none'
                  " [ngStyle]="{
                    height:
                      openSubmenu === 'others-' + i
                        ? (subMenuHeights['others-' + i] || 0) + 'px'
                        : '0px'
                  }">
                <ul class="mt-2 space-y-1 ml-9">
                  @for (subItem of nav.subItems; track $index) {
                  <li>
                    <a [routerLink]="subItem.path" routerLinkActive="" (click)="onSubmenuClick()"
                      class="menu-dropdown-item" [ngClass]="{
                              'menu-dropdown-item-inactive': !isActive(subItem.path),
                              'menu-dropdown-item-active': isActive(subItem.path),
                            }">
                      {{ subItem.name }}
                      <span class="flex items-center gap-1 ml-auto">
                        @if (subItem.new) {
                        <span class="menu-dropdown-badge" [ngClass]="{
                              'menu-dropdown-badge-active': isActive(
                                subItem.path
                              ),
                              'menu-dropdown-badge-inactive': !isActive(
                                subItem.path
                              )
                            }">
                          new
                        </span>
                        }
                        @if (subItem.pro) {
                        <span class="ml-auto menu-dropdown-badge-pro" [ngClass]="{
                              'menu-dropdown-badge-pro-active': isActive(
                                subItem.path
                              ),
                              'menu-dropdown-badge-pro-inactive': !isActive(
                                subItem.path
                              )
                            }">
                          pro
                        </span>
                        }
                      </span>
                    </a>
                  </li>
                  }
                </ul>
              </div>
              } @else {
              @if (nav.path) {
              <a [routerLink]="nav.path" routerLinkActive="menu-item-active" class="menu-item group"
                [ngClass]="{ 'menu-item-inactive': !isActive(nav.path) }">
                <span class="menu-item-icon-size" [ngClass]="{
                      'menu-item-icon-active': isActive(nav.path),
                      'menu-item-icon-inactive': !isActive(nav.path)
                    }" [innerHTML]="nav.icon | safeHtml">
                </span>
                <span class="menu-item-text">
                  @if ((isExpanded$ | async) || (isHovered$ | async) || (isMobileOpen$ | async)) {
                  {{ nav.name }}
                  }
                </span>
              </a>
              }
              }
            </li>
            }
          </ul>
        </div>
        <!-- end other section -->
      </div>
    </nav>
    @if ((isExpanded$ | async) || (isHovered$ | async) || (isMobileOpen$ | async)) {
    <app-sidebar-widget />
    }
  </div>
</aside>
