// apps/web/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../core/services/auth.service';

@Component({
    selector: 'app-login',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule],
    template: `
    <div class="min-h-screen bg-gradient-to-br from-primary-50 to-primary-100 flex items-center justify-center px-4">
      <div class="bg-white rounded-lg shadow-xl p-8 w-full max-w-md">
        <!-- Logo y título -->
        <div class="text-center mb-8">
          <h1 class="text-3xl font-bold text-primary-900 mb-2">CERMONT</h1>
          <p class="text-gray-600">Sistema de Gestión de Órdenes</p>
        </div>

        <!-- Formulario -->
        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
          <!-- Email -->
          <div class="mb-6">
            <label class="block text-sm font-semibold text-gray-700 mb-2">
              Correo Electrónico
            </label>
            <input
              type="email"
              formControlName="email"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              placeholder="tu@correo.com"
            />
            <div
              *ngIf="email.invalid && email.touched"
              class="text-red-500 text-sm mt-1"
            >
              Email inválido
            </div>
          </div>

          <!-- Password -->
          <div class="mb-6">
            <label class="block text-sm font-semibold text-gray-700 mb-2">
              Contraseña
            </label>
            <input
              type="password"
              formControlName="password"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              placeholder="••••••••"
            />
            <div
              *ngIf="password.invalid && password.touched"
              class="text-red-500 text-sm mt-1"
            >
              La contraseña es requerida
            </div>
          </div>

          <!-- Botón Login -->
          <button
            type="submit"
            [disabled]="!loginForm.valid || isLoading"
            class="w-full bg-primary-500 text-white py-2 rounded-lg font-semibold hover:bg-primary-600 transition disabled:opacity-50"
          >
            {{ isLoading ? 'Iniciando sesión...' : 'Iniciar Sesión' }}
          </button>

          <!-- Mensaje de error -->
          <div
            *ngIf="errorMessage"
            class="mt-4 p-3 bg-red-100 text-red-700 rounded-lg text-sm"
          >
            {{ errorMessage }}
          </div>
        </form>
      </div>
    </div>
  `,
})
export class LoginComponent implements OnInit {
    loginForm: FormGroup;
    isLoading = false;
    errorMessage = '';

    constructor(
        private fb: FormBuilder,
        private authService: AuthService,
        private router: Router
    ) {
        this.loginForm = this.fb.group({
            email: ['', [Validators.required, Validators.email]],
            password: ['', [Validators.required, Validators.minLength(6)]],
        });
    }

    ngOnInit(): void {
        // Si ya está autenticado, redirigir al dashboard
        if (this.authService.isAuthenticated()) {
            this.router.navigate(['/dashboard']);
        }
    }

    get email() {
        return this.loginForm.get('email')!;
    }

    get password() {
        return this.loginForm.get('password')!;
    }

    onSubmit(): void {
        if (!this.loginForm.valid) {
            return;
        }

        this.isLoading = true;
        this.errorMessage = '';

        const { email, password } = this.loginForm.value;

        this.authService.login({ email, password }).subscribe({
            next: () => {
                this.router.navigate(['/dashboard']);
            },
            error: (error) => {
                this.errorMessage = error.error?.message || 'Error al iniciar sesión';
                this.isLoading = false;
            },
        });
    }
}

// apps/frontend/src/app/(auth)/login/page.tsx
'use client';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import Image from 'next/image';
import { useLoginForm } from '@/lib/auth/useLoginForm';

export default function LoginPage() {
  const { form, globalError, onSubmit, isSubmitting } = useLoginForm();
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = form;

  return (
    <div className="grid min-h-screen place-items-center p-4">
      <div className="w-full max-w-md space-y-8 rounded-lg bg-white p-8 shadow-lg">
        {/* Header con logo */}
        <div className="text-center">
          <div className="mb-4 flex items-center justify-center">
            <Image src="/logo-cermont.png" alt="Cermont ATG" width={128} height={128} className="h-16 w-auto" priority />
          </div>
          <h1 className="text-2xl font-semibold text-gray-900">
            Bienvenido
          </h1>
          <p className="mt-2 text-sm text-gray-600">
            Sistema de Gestión de Trabajos
          </p>
        </div>

        {/* Formulario */}
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          {/* Error global */}
          {globalError && (
            <div
              role="alert"
              className="rounded-md border border-red-200 bg-red-50 p-3"
            >
              <p className="text-sm text-red-800">{globalError}</p>
            </div>
          )}

          {/* Campo Email */}
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              placeholder="tu@email.com"
              aria-invalid={!!errors.email}
              aria-describedby={errors.email ? 'email-error' : undefined}
              disabled={isSubmitting}
              {...register('email')}
            />
            {errors.email && (
              <p id="email-error" className="text-sm text-red-600">
                {errors.email.message}
              </p>
            )}
          </div>

          {/* Campo Password */}
          <div className="space-y-2">
            <Label htmlFor="password">Contraseña</Label>
            <Input
              id="password"
              type="password"
              placeholder="••••••••"
              aria-invalid={!!errors.password}
              aria-describedby={errors.password ? 'password-error' : undefined}
              disabled={isSubmitting}
              {...register('password')}
            />
            {errors.password && (
              <p id="password-error" className="text-sm text-red-600">
                {errors.password.message}
              </p>
            )}
          </div>

          {/* Botón Submit */}
          <Button
            type="submit"
            disabled={isSubmitting}
            className="w-full"
            aria-busy={isSubmitting}
          >
            {isSubmitting ? (
              <span className="flex items-center gap-2">
                <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
                Iniciando sesión...
              </span>
            ) : (
              'Iniciar Sesión'
            )}
          </Button>
        </form>

        {/* Credenciales de prueba */}
        {process.env.NODE_ENV === 'development' && (
          <div className="rounded-md border border-blue-200 bg-blue-50 p-3 text-center text-xs text-blue-700">
            <p className="font-medium">Credenciales de prueba:</p>
            <p className="mt-1 font-mono">admin@cermont.com / admin123</p>
          </div>
        )}
      </div>
    </div>
  );
}
