// web/src/components/landing/LandingFooter.tsx
import Link from 'next/link';
import Image from 'next/image';

const footerLinks = {
    servicios: [
        { label: 'Construcción', href: '#servicios' },
        { label: 'Electricidad', href: '#servicios' },
        { label: 'Refrigeración', href: '#servicios' },
        { label: 'Montajes', href: '#servicios' },
        { label: 'Suministros', href: '#servicios' },
    ],
    empresa: [
        { label: 'Sobre Nosotros', href: '#nosotros' },
        { label: 'Misión y Visión', href: '#nosotros' },
        { label: 'Valores', href: '#nosotros' },
        { label: 'Certificaciones', href: '#nosotros' },
    ],
    recursos: [
        { label: 'Sistema de Gestión', href: '/login' },
        { label: 'SG-SST', href: '#' },
        { label: 'PESV', href: '#' },
        { label: 'Políticas', href: '#' },
    ],
};

export default function LandingFooter() {
    return (
        <footer className="bg-gray-900 dark:bg-gray-950 text-gray-400">
            {/* Main Footer */}
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-8 lg:gap-12">
                    {/* Brand Column */}
                    <div className="col-span-2 md:col-span-1">
                        <Link href="/" className="flex items-center gap-3 mb-6">
                            <div className="relative w-10 h-10">
                                <Image
                                    src="/logo.svg"
                                    alt="Cermont Logo"
                                    fill
                                    className="object-contain"
                                />
                            </div>
                            <span className="text-xl font-bold text-white">CERMONT</span>
                        </Link>
                        <p className="text-sm leading-relaxed mb-6">
                            Soluciones integrales en construcción, electricidad, refrigeración,
                            montajes y suministros con más de 15 años de experiencia.
                        </p>
                        {/* Social Links */}
                        <div className="flex gap-3">
                            <a
                                href="#"
                                className="w-10 h-10 rounded-lg bg-gray-800 hover:bg-gray-700 flex items-center justify-center transition-colors"
                                aria-label="Facebook"
                            >
                                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                                    <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
                                </svg>
                            </a>
                            <a
                                href="#"
                                className="w-10 h-10 rounded-lg bg-gray-800 hover:bg-gray-700 flex items-center justify-center transition-colors"
                                aria-label="LinkedIn"
                            >
                                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                                    <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                                </svg>
                            </a>
                            <a
                                href="#"
                                className="w-10 h-10 rounded-lg bg-gray-800 hover:bg-gray-700 flex items-center justify-center transition-colors"
                                aria-label="Instagram"
                            >
                                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                                    <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z" />
                                </svg>
                            </a>
                        </div>
                    </div>

                    {/* Services Column */}
                    <div>
                        <h3 className="text-white font-semibold mb-4">Servicios</h3>
                        <ul className="space-y-3">
                            {footerLinks.servicios.map((link, index) => (
                                <li key={index}>
                                    <a
                                        href={link.href}
                                        className="text-sm hover:text-white transition-colors"
                                    >
                                        {link.label}
                                    </a>
                                </li>
                            ))}
                        </ul>
                    </div>

                    {/* Company Column */}
                    <div>
                        <h3 className="text-white font-semibold mb-4">Empresa</h3>
                        <ul className="space-y-3">
                            {footerLinks.empresa.map((link, index) => (
                                <li key={index}>
                                    <a
                                        href={link.href}
                                        className="text-sm hover:text-white transition-colors"
                                    >
                                        {link.label}
                                    </a>
                                </li>
                            ))}
                        </ul>
                    </div>

                    {/* Resources Column */}
                    <div>
                        <h3 className="text-white font-semibold mb-4">Recursos</h3>
                        <ul className="space-y-3">
                            {footerLinks.recursos.map((link, index) => (
                                <li key={index}>
                                    <Link
                                        href={link.href}
                                        className="text-sm hover:text-white transition-colors"
                                    >
                                        {link.label}
                                    </Link>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </div>

            {/* Bottom Bar */}
            <div className="border-t border-gray-800">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
                    <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
                        <p className="text-sm">
                            © {new Date().getFullYear()} CERMONT S.A.S. Todos los derechos reservados.
                        </p>
                        <div className="flex gap-6">
                            <a href="#" className="text-sm hover:text-white transition-colors">
                                Política de Privacidad
                            </a>
                            <a href="#" className="text-sm hover:text-white transition-colors">
                                Términos de Servicio
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    );
}

// apps/web/src/app/shared/components/landing/landing-footer/landing-footer.component.ts
/**
 * Landing Footer Component - Migrado de Next.js
 * @see apps/web-old/src/components/landing/LandingFooter.tsx
 */

import { Component } from '@angular/core';

import { RouterModule } from '@angular/router';

interface FooterLink {
  label: string;
  href: string;
}

@Component({
  selector: 'app-landing-footer',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './landing-footer.component.html',
  styleUrl: './landing-footer.component.css'
})
export class LandingFooterComponent {
  currentYear = new Date().getFullYear();

  footerLinks = {
    servicios: [
      { label: 'Construcción', href: '#servicios' },
      { label: 'Electricidad', href: '#servicios' },
      { label: 'Refrigeración', href: '#servicios' },
      { label: 'Montajes', href: '#servicios' },
      { label: 'Suministros', href: '#servicios' },
    ],
    empresa: [
      { label: 'Sobre Nosotros', href: '#nosotros' },
      { label: 'Misión y Visión', href: '#nosotros' },
      { label: 'Valores', href: '#nosotros' },
      { label: 'Certificaciones', href: '#nosotros' },
    ],
    recursos: [
      { label: 'Sistema de Gestión', href: '/signin' },
      { label: 'SG-SST', href: '#' },
      { label: 'PESV', href: '#' },
      { label: 'Políticas', href: '#' },
    ],
  };

  scrollToSection(sectionId: string, event: Event): void {
    event.preventDefault();
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }
}


<footer class="bg-gray-900 dark:bg-gray-950 text-gray-400">
  <!-- Main Footer -->
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
    <div class="grid grid-cols-2 md:grid-cols-4 gap-8 lg:gap-12">
      <!-- Brand Column -->
      <div class="col-span-2 md:col-span-1">
        <a routerLink="/" class="flex items-center gap-3 mb-6">
          <div class="relative w-10 h-10">
            <img src="/logo.svg" alt="Cermont Logo" class="w-full h-full object-contain" />
          </div>
          <span class="text-xl font-bold text-white">CERMONT</span>
        </a>
        <p class="text-sm leading-relaxed mb-6">
          Soluciones integrales en construcción, electricidad, refrigeración,
          montajes y suministros con más de 15 años de experiencia.
        </p>
        <!-- Social Links -->
        <div class="flex gap-3">
          <a
            href="#"
            class="w-10 h-10 rounded-lg bg-gray-800 hover:bg-gray-700 flex items-center justify-center transition-colors"
            aria-label="Facebook">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
            </svg>
          </a>
          <a
            href="#"
            class="w-10 h-10 rounded-lg bg-gray-800 hover:bg-gray-700 flex items-center justify-center transition-colors"
            aria-label="LinkedIn">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
            </svg>
          </a>
          <a
            href="#"
            class="w-10 h-10 rounded-lg bg-gray-800 hover:bg-gray-700 flex items-center justify-center transition-colors"
            aria-label="Instagram">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z" />
            </svg>
          </a>
        </div>
      </div>

      <!-- Services Column -->
      <div>
        <h3 class="text-white font-semibold mb-4">Servicios</h3>
        <ul class="space-y-3">
          @for (link of footerLinks.servicios; track link.label) {
            <li>
              <a
                (click)="scrollToSection('servicios', $event)"
                class="text-sm hover:text-white transition-colors cursor-pointer">
                {{ link.label }}
              </a>
            </li>
          }
        </ul>
      </div>

      <!-- Company Column -->
      <div>
        <h3 class="text-white font-semibold mb-4">Empresa</h3>
        <ul class="space-y-3">
          @for (link of footerLinks.empresa; track link.label) {
            <li>
              <a
                (click)="scrollToSection('nosotros', $event)"
                class="text-sm hover:text-white transition-colors cursor-pointer">
                {{ link.label }}
              </a>
            </li>
          }
        </ul>
      </div>

      <!-- Resources Column -->
      <div>
        <h3 class="text-white font-semibold mb-4">Recursos</h3>
        <ul class="space-y-3">
          @for (link of footerLinks.recursos; track link.label) {
            <li>
              @if (link.href.startsWith('/')) {
                <a
                  [routerLink]="link.href"
                  class="text-sm hover:text-white transition-colors">
                  {{ link.label }}
                </a>
              } @else {
                <a
                  [href]="link.href"
                  class="text-sm hover:text-white transition-colors">
                  {{ link.label }}
                </a>
              }
            </li>
          }
        </ul>
      </div>
    </div>
  </div>

  <!-- Bottom Bar -->
  <div class="border-t border-gray-800">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
      <div class="flex flex-col sm:flex-row justify-between items-center gap-4">
        <p class="text-sm">
          © {{ currentYear }} CERMONT S.A.S. Todos los derechos reservados.
        </p>
        <div class="flex gap-6">
          <a href="#" class="text-sm hover:text-white transition-colors">
            Política de Privacidad
          </a>
          <a href="#" class="text-sm hover:text-white transition-colors">
            Términos de Servicio
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>
